
<%--
(ref: jsp/jsp.jsp.et.jsp)
-------------------------------------
$Revision:   $
$Date:  $
$Author:  $Generated by Engineer, Enhanced by Sandeep
$Modtime: $

Version History:
-------------------------------------
$Log:$
--%>
<%@ page language="java"%>
<%@ page import="com.cdoe.ui.*"%>
<%@ page import="com.cdoe.biz.*"%>
<%@ page import="com.cdoe.util.*"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>

<%-- Wrap the entire JSP in a try/catch block so that runtime exceptions
    in the JSP can be caught and reported. --%>
<%@include file="/WEB-INF/jsp/JspTry.inc"%>

<%
    String prevFiscalYear = DateUtil.getPrevFiscalYear();
	String formattedFiscalYear = DateUtil.getFiscalYearFormattedLong(prevFiscalYear);
    UserInfo userInfo = (UserInfo) session.getAttribute("USER_INFO");
%>
<script type='text/javascript'>
	$(document)
			.ready(
					function() {
						$('#TotalCurrentOperatingExp')
								.focus(
										function() {
											$('#hintRI')
													.html(
															"For assistance, please use the CDE-40 Worksheet.");
											$('#hintRI').show();
											//$('#hintRI').css("marginTop", "1em");
											return false;
										});
						$('#TotalCurrentOperatingExp').blur(function() {
							$('#hintRI').hide();
							checkAndFormatAmount('TotalCurrentOperatingExp');
							return false;
						});
						$('#MigMilesOfTransportation')
								.focus(
										function() {
											$('#hintRI')
													.html(
															"Complete the Migrant Verification Form if miles are reported on Line 2");
											$('#hintRI').show();
											//$('#hintRI').css("marginTop", "1em");
											return false;
										});
						$('#MigMilesOfTransportation').blur(function() {
							$('#hintRI').hide();
							formatMileageField('MigMilesOfTransportation');
							return false;
						});
						$('#regDMiles')
								.focus(
										function() {
											$('#hintRI')
													.html(
															"Includes all miles driven on the mileage count date when establishing routes for all eligible pupils. Same date as official pupil count date.<br/>If reporting parent miles, parent must have made the trip on September 30th 2011.");
											$('#hintRI').show();
											//$('#hintRI').css("marginTop", "1em");
											return false;
										});
						$('#regDMiles').blur(function() {
							$('#hintRI').hide();
							formatMileageField('regDMiles');
							return false;
						});
						$('#DaysSchoolWasInSession')
								.focus(
										function() {
											$('#hintRI')
													.html(
															"Remember to remove snow and mud days.");
											$('#hintRI').show();
											//$('#hintRI').css("marginTop", "1em");
											return false;
										});
						$('#DaysSchoolWasInSession').blur(function() {
							$('#hintRI').hide();
							return false;
						});
						$('#NosOfPupilSchedules')
								.focus(
										function() {
											$('#hintAI')
													.html(
															"Report the number of students that the routes are set up for: total eligibility.");
											$('#hintAI').show();
											//$('#hintAI').css("marginTop", "1em");
											return false;
										});
						$('#NosOfPupilSchedules').blur(function() {
							$('#hintAI').hide();
							return false;
						});
						$('#TotalActualMilesTravelled')
								.focus(
										function() {
											$('#hintAI')
													.html(
															"Entitlement Period:<br/>July 1, 2011 through June 30, 2012");
											$('#hintAI').show();
											//$('#hintAI').css("marginTop", "1em");
											return false;
										});
						$('#TotalActualMilesTravelled').blur(function() {
							$('#hintAI').hide();
							return false;
						});
						$('#TotalActualMilesTraveledForAnyPurpose')
								.focus(
										function() {
											$('#hintAI')
													.html(
															"If pupil transportation vehicles are also used for other purposes (administrative), exclude the miles for other purposes.<br/><br/>Total Odometer Miles: Pupil Transportation Vehicles Only.");
											$('#hintAI').show();
											//$('#hintAI').css("marginTop", "1em");
											return false;
										});
						$('#TotalActualMilesTraveledForAnyPurpose')
								.blur(
										function() {
											$('#hintAI').hide();
											formatMileageField('TotalActualMilesTraveledForAnyPurpose');
											return false;
										});
						$('#FeesCollected')
								.focus(
										function() {
											$('#hintAI')
													.html(
															"Do not include transportation fees collected for activities.");
											$('#hintAI').show();
											//$('#hintAI').css("marginTop", "1em");
											return false;
										});
						$('#FeesCollected').blur(function() {
							$('#hintAI').hide();
							checkAndFormatAmount('FeesCollected');
							return false;
						});
					});
</script>


<script language="javascript" type="text/javascript">
	function saveData() {
		if (document.getElementById("isCapitalOutLay") == null || document.getElementById("isCapitalOutLay").value == "false")
			alert("Your CDE-40 Form has been completed. A pdf copy of the CDE-40 will be emailed to the email address provided on this form. If any changes need to be made to this CDE-40 Form, please contact the Colorado Department of Education: 303-866-6843");
	    else
	        alert("You will need to complete the Capital Outlay Form also. Saving data and transferring to Capital Outlay");
	
	}
</script>


<div id="mainContent">
	<form:form commandName="transportationForm"
		action="${pageContext.request.contextPath}/secure/Cde40TransReimbForm/save"
		method="post">

		<!-- Main outer table -->
		</br>
		<h2>
			<spring:message
				code="Cde40TransReimbForm.StaticText.reimbursementClaimsForEntitlementPeriodStaticText" />
			&nbsp;<%=formattedFiscalYear%>
		</h2>
		<font color="red"><c:out id="Message" value="${transportationForm.message}"/></font>
		<TABLE>
			<TR>
				<TD>
					<div class="formBlock boxShadow3 radius10">
						    <h3><spring:message  code="Cde40TransReimbForm.StaticText.nameOfPersonPreparingTheReportStaticText" /></h3>
							<div style='float: left;'>
								<span class="field" style='width: 100px;'><label
									for="namePreparerCde40">Name</label></span> <span class="bodyText"
									style='width: 350px;'> <form:input id=""
										path="namePreparerCde40" size="25" maxlength="100" /><font color="red"><b>*</b></font>
								</span> <br /> 
								<span class="field" style='width: 100px;'>
								<LABEL FOR="">Email Address</LABEL> 
								</span> <span class="bodyText"
									style='width: 350px;'> <form:input id=""
										path="emailPreparerCde40" size="40" maxlength="100"
										onBlur="validateEmail('emailPreparerCde40')" />
										<font color="red"><b>*</b></font>
								</span> <br />
							    <span class="field" style='width: 100px;'>
							    <label
									for="phonePreparerCde40">Phone</label></span> 
									<span class="bodyText"
									style='width: 350px;'> <form:input id=""
										path="phonePreparerCde40" size="16" maxlength="16"
										onBlur="validatePhoneNos('phonePreparerCde40')" />
										<font color="red"><b>*</b></font>
								</span>
							</div>
							<div
								style='float: left; background-color: #fafafa; border: 1px solid #ddd; padding: 0.5em 1em;'
								class='radius5'>
								<span class="field" style='width: 120px;'>
									<label for="districtNumber">District Number</label>
								</span> 
								<span	class="bodyText"> 
									<form:input id="DistrictNumber"	path="districtNumber" size="12" maxlength="12" readonly="true" />
								</span> <br /> 
								<span class="field" style='width: 120px;'>
									<label for="districtName">District Name</label>
								</span> 
								<span class="bodyText">
									<form:input id="DistrictName" path="districtName" size="26"	maxlength="41" readonly="true"/>
								</span>
							</div>
							<div style='clear: both;'></div>
						</div>
						
						<TABLE>
							<!-- div id='hintRI' class="hint boxShadow3 radius5 right" --> 
						 	<TR>
						 		
								<TD COLSPAN="6"><h3><b><spring:message
											code="Cde40TransReimbForm.StaticText.reimbursementInformationStaticText" /></h3></b>
								</TD>
								<TD><form:hidden path="id" /><form:hidden id="isCapitalOutLay" path="isCapitalOutLay" /></TD>
							</TR>
							
							<TR>
								
								<TD width="78%">&nbsp;&nbsp;<spring:message
										code="Cde40TransReimbForm.StaticText.$1aTotalCurrentOperatingExpendituresForPupilTransportationStaticText" />
								</TD>

								<TD>
									$<form:input id="TotalCurrentOperatingExp"
										path="operTran" 
										onBlur="checkAndFormatAmount('TotalCurrentOperatingExp')"/><font color="red"><b>*</b> 
										<form:errors path="operTran" cssClass="validationError" /></font>
									</div>
								</TD>
							</TR>

							<TR>
								<TD width="78%">&nbsp;&nbsp;<spring:message
										code="Cde40TransReimbForm.StaticText.$2MileageTraveledForTransportingMigrantEducationPupilsStaticText" />
								</TD>
								<TD><form:input id="MigMilesOfTransportation"
										path="migMiles"
										onBlur="formatMileageField('MigMilesOfTransportation')" /><font color="red"><b>*</b> <form:errors
										path="migMiles" cssClass="validationError" /></font></td>
							</TR>
							<TR>
								<TD width="78%">&nbsp;&nbsp;<LABEL FOR=""><spring:message
											code="Cde40TransReimbForm.StaticText.$3MileageScheduledForRegularPupilTransportationOnTheMileageCountDateStaticText" /></LABEL>
								</TD>
								<TD><form:input id="regDMiles" path="regDMiles"
										onBlur="formatMileageField('regDMiles')" /><font color="red"><b>*</b>  <form:errors
										path="regDMiles" cssClass="validationError" /></font></TD>
							</TR>
							<TR>
								<TD width="78%">&nbsp;&nbsp;<spring:message
										code="Cde40TransReimbForm.StaticText.$4DaysSchoolWasInSessionAndPupilsWereTransportedInTheSchoolTermStaticText" />
								</TD>
								<TD><form:input id="DaysSchoolWasInSession"
										path="schoolDays" /><font color="red"><b>*</b>  <form:errors path="schoolDays"
										cssClass="validationError" /></font></td>
							</TR>

							<TR>
								<TD width="78%">&nbsp;&nbsp;<LABEL FOR=""><spring:message
											code="Cde40TransReimbForm.StaticText.$5NumberOfDaysForWhichRoomAndBoardWasPaidForPupilsInLieuOfTransportationStaticText" /></LABEL>
								</TD>
								<TD><form:input id="" path="boardTran" /><form:errors
										path="boardTran" cssClass="validationError" /></td>
							</TR>


							<TR>
								<TD width="78%">&nbsp;&nbsp;<spring:message
										code="Cde40TransReimbForm.StaticText.$6NumberOfPupilsScheduledToBeTransportedToAndFromPublicSchoolAtPublicStaticText" />
								</TD>
							</TR>
							<TR>
								<TD width="78%">&nbsp;&nbsp;<spring:message
										code="Cde40TransReimbForm.StaticText.expenseOnTheMileageCountDateStaticText" />
								</TD>
								<TD><form:input id="NosOfPupilSchedules" path="pupilTran" /><font color="red"><b>*</b> 
									<form:errors path="pupilTran" cssClass="validationError" /></font></TD>
							</TR>

							<TR>
								<TD width="78%">&nbsp;&nbsp;<spring:message
										code="Cde40TransReimbForm.StaticText.$7TotalActualMilesTraveledForActivityTripsFieldTripsAthleticTripsEtcDuringEntitlementPeriodStaticText" />
								</TD>
								<TD><form:input id="TotalActualMilesTravelled"
										path="actMiles"
										onBlur="formatMileageField('TotalActualMilesTravelled')" /><font color="red"><b>*</b> <form:errors
										path="actMiles" cssClass="validationError" /></font></TD>
							</TR>

							<TR>
								<TD width="78%">&nbsp;&nbsp;<spring:message
										code="Cde40TransReimbForm.StaticText.$8TotalActualMilesTraveledForAnyPurposeByPupilTransportationVehiclesDuringEntitlementPeriodStaticText" />
								</TD>
								<TD><form:input id="TotalActualMilesTraveledForAnyPurpose"
										path="totalMiles"
										onBlur="formatMileageField('TotalActualMilesTraveledForAnyPurpose')" /><font color="red"><b>*</b> 
									<form:errors path="totalMiles" cssClass="validationError" /></font></TD>
							</TR>
					<!-- /div> -->
					</TABLE>
					
					
						</br>
						<TABLE>
							<TR>
								<TD width="48%"></TD>
								<TD align="center" colspan="4"><input type="Submit"
									id="saveButton" value="Save/Electronics Signature"
									onclick="saveData()" /></TD>
							</TR>
						</TABLE>
						</div>
				</TD>
			</TR>
		</TABLE>
	</form:form>
</div>
<script type="text/javascript"
	src="${pageContext.request.contextPath}/static/scripts/screen/Cde40TransReimbForm.js"></script>
<%-- End of try/catch around complete JSP in order to log and display
     runtime exceptions that occur in the JSP. --%>
<%@include file="/WEB-INF/jsp/JspCatch.inc"%>