
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`AUD_FPC_LUN`")
public class AudFpcLun implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`S_FUNDED_CNT_K`")
	private Long sFundedCntK;

    public Long getSFundedCntK () {
        return this.sFundedCntK;
    }

    public void setSFundedCntK (Long sFundedCntK) {
        this.sFundedCntK = sFundedCntK;
    }

	@Column(name = "`S_CPKP_CNT`")
	private Long sCpkpCnt;

    public Long getSCpkpCnt () {
        return this.sCpkpCnt;
    }

    public void setSCpkpCnt (Long sCpkpCnt) {
        this.sCpkpCnt = sCpkpCnt;
    }

	@Column(name = "`S_MEM_K_12_CNT`")
	private Double sMemK12Cnt;

    public Double getSMemK12Cnt () {
        return this.sMemK12Cnt;
    }

    public void setSMemK12Cnt (Double sMemK12Cnt) {
        this.sMemK12Cnt = sMemK12Cnt;
    }

	@Column(name = "`S_MEM_1_8_CNT`")
	private Double sMem18Cnt;

    public Double getSMem18Cnt () {
        return this.sMem18Cnt;
    }

    public void setSMem18Cnt (Double sMem18Cnt) {
        this.sMem18Cnt = sMem18Cnt;
    }

	@Column(name = "`S_FL_K_12_CNT`")
	private Double sFlK12Cnt;

    public Double getSFlK12Cnt () {
        return this.sFlK12Cnt;
    }

    public void setSFlK12Cnt (Double sFlK12Cnt) {
        this.sFlK12Cnt = sFlK12Cnt;
    }

	@Column(name = "`S_FL_1_8_CNT`")
	private Double sFl18Cnt;

    public Double getSFl18Cnt () {
        return this.sFl18Cnt;
    }

    public void setSFl18Cnt (Double sFl18Cnt) {
        this.sFl18Cnt = sFl18Cnt;
    }

	@Column(name = "`S_ONLINE_CNT`")
	private Double sOnlineCnt;

    public Double getSOnlineCnt () {
        return this.sOnlineCnt;
    }

    public void setSOnlineCnt (Double sOnlineCnt) {
        this.sOnlineCnt = sOnlineCnt;
    }

	@Column(name = "`S_LUNCH_CNT`")
	private Double sLunchCnt;

    public Double getSLunchCnt () {
        return this.sLunchCnt;
    }

    public void setSLunchCnt (Double sLunchCnt) {
        this.sLunchCnt = sLunchCnt;
    }

	@Column(name = "`S_FUNDED_CNT`")
	private Double sFundedCnt;

    public Double getSFundedCnt () {
        return this.sFundedCnt;
    }

    public void setSFundedCnt (Double sFundedCnt) {
        this.sFundedCnt = sFundedCnt;
    }

	@Column(name = "`SNUMBER`")
	private Double snumber;

    public Double getSnumber () {
        return this.snumber;
    }

    public void setSnumber (Double snumber) {
        this.snumber = snumber;
    }

	@Column(name = "`CHANGE_TYPE`")
	private String changeType;

    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

	@Column(name = "`DATE_CHANGED`")
	private String dateChanged;

    public String getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (String dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

}