
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`AUDIT_TRACKING`")
public class AuditTracking implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`SUPERVISOR`")
	private String supervisor;

    public String getSupervisor () {
        return this.supervisor;
    }

    public void setSupervisor (String supervisor) {
        this.supervisor = supervisor;
    }

	@Column(name = "`SECONDARY_AUDITOR_COMMENTS`")
	private String secondaryAuditorComments;

    public String getSecondaryAuditorComments () {
        return this.secondaryAuditorComments;
    }

    public void setSecondaryAuditorComments (String secondaryAuditorComments) {
        this.secondaryAuditorComments = secondaryAuditorComments;
    }

	@Column(name = "`FINALIZED_BY`")
	private String finalizedBy;

    public String getFinalizedBy () {
        return this.finalizedBy;
    }

    public void setFinalizedBy (String finalizedBy) {
        this.finalizedBy = finalizedBy;
    }

	@Column(name = "`REVIEWED_BY`")
	private String reviewedBy;

    public String getReviewedBy () {
        return this.reviewedBy;
    }

    public void setReviewedBy (String reviewedBy) {
        this.reviewedBy = reviewedBy;
    }

	@Column(name = "`RECLOSED_AFTER_APPEAL`")
	private Date reclosedAfterAppeal;

    public Date getReclosedAfterAppeal () {
        return this.reclosedAfterAppeal;
    }

    public void setReclosedAfterAppeal (Date reclosedAfterAppeal) {
        this.reclosedAfterAppeal = reclosedAfterAppeal;
    }

	@Column(name = "`AUDIT_REFINALIZED`")
	private Date auditRefinalized;

    public Date getAuditRefinalized () {
        return this.auditRefinalized;
    }

    public void setAuditRefinalized (Date auditRefinalized) {
        this.auditRefinalized = auditRefinalized;
    }

	@Column(name = "`AUDIT_REOPENED`")
	private Date auditReopened;

    public Date getAuditReopened () {
        return this.auditReopened;
    }

    public void setAuditReopened (Date auditReopened) {
        this.auditReopened = auditReopened;
    }

	@Column(name = "`AUDIT_CLOSED`")
	private Date auditClosed;

    public Date getAuditClosed () {
        return this.auditClosed;
    }

    public void setAuditClosed (Date auditClosed) {
        this.auditClosed = auditClosed;
    }

	@Column(name = "`REPORT_APPEALED`")
	private Date reportAppealed;

    public Date getReportAppealed () {
        return this.reportAppealed;
    }

    public void setReportAppealed (Date reportAppealed) {
        this.reportAppealed = reportAppealed;
    }

	@Column(name = "`DRAFT_REPORT_ISSUED`")
	private Date draftReportIssued;

    public Date getDraftReportIssued () {
        return this.draftReportIssued;
    }

    public void setDraftReportIssued (Date draftReportIssued) {
        this.draftReportIssued = draftReportIssued;
    }

	@Column(name = "`DRAFT_REPORT_COMPLETED`")
	private Date draftReportCompleted;

    public Date getDraftReportCompleted () {
        return this.draftReportCompleted;
    }

    public void setDraftReportCompleted (Date draftReportCompleted) {
        this.draftReportCompleted = draftReportCompleted;
    }

	@Column(name = "`INITIAL_FIELD_WORK_COMPLETED`")
	private Date initialFieldWorkCompleted;

    public Date getInitialFieldWorkCompleted () {
        return this.initialFieldWorkCompleted;
    }

    public void setInitialFieldWorkCompleted (Date initialFieldWorkCompleted) {
        this.initialFieldWorkCompleted = initialFieldWorkCompleted;
    }

	@Column(name = "`FIELD_WORK_STARTED`")
	private Date fieldWorkStarted;

    public Date getFieldWorkStarted () {
        return this.fieldWorkStarted;
    }

    public void setFieldWorkStarted (Date fieldWorkStarted) {
        this.fieldWorkStarted = fieldWorkStarted;
    }

	@Column(name = "`DISTRICT_CONTACTED`")
	private Date districtContacted;

    public Date getDistrictContacted () {
        return this.districtContacted;
    }

    public void setDistrictContacted (Date districtContacted) {
        this.districtContacted = districtContacted;
    }

	@Column(name = "`TOTAL_AUDIT_LIABILITY`")
	private Double totalAuditLiability;

    public Double getTotalAuditLiability () {
        return this.totalAuditLiability;
    }

    public void setTotalAuditLiability (Double totalAuditLiability) {
        this.totalAuditLiability = totalAuditLiability;
    }

	@Column(name = "`REPORT_FINALIZED`")
	private Date reportFinalized;

    public Date getReportFinalized () {
        return this.reportFinalized;
    }

    public void setReportFinalized (Date reportFinalized) {
        this.reportFinalized = reportFinalized;
    }

	@Column(name = "`PRIMARY_AUDITOR_COMMENTS`")
	private String primaryAuditorComments;

    public String getPrimaryAuditorComments () {
        return this.primaryAuditorComments;
    }

    public void setPrimaryAuditorComments (String primaryAuditorComments) {
        this.primaryAuditorComments = primaryAuditorComments;
    }

	@Column(name = "`SUPERVISOR_COMMENTS`")
	private String supervisorComments;

    public String getSupervisorComments () {
        return this.supervisorComments;
    }

    public void setSupervisorComments (String supervisorComments) {
        this.supervisorComments = supervisorComments;
    }

	@Column(name = "`AUDIT_TYPE`")
	private String auditType;

    public String getAuditType () {
        return this.auditType;
    }

    public void setAuditType (String auditType) {
        this.auditType = auditType;
    }

	@Column(name = "`OPEN_DATE`")
	private Date openDate;

    public Date getOpenDate () {
        return this.openDate;
    }

    public void setOpenDate (Date openDate) {
        this.openDate = openDate;
    }

	@Column(name = "`FISCAL_YEAR_5`")
	private String fiscalYear5;

    public String getFiscalYear5 () {
        return this.fiscalYear5;
    }

    public void setFiscalYear5 (String fiscalYear5) {
        this.fiscalYear5 = fiscalYear5;
    }

	@Column(name = "`FISCAL_YEAR_4`")
	private String fiscalYear4;

    public String getFiscalYear4 () {
        return this.fiscalYear4;
    }

    public void setFiscalYear4 (String fiscalYear4) {
        this.fiscalYear4 = fiscalYear4;
    }

	@Column(name = "`FISCAL_YEAR_3`")
	private String fiscalYear3;

    public String getFiscalYear3 () {
        return this.fiscalYear3;
    }

    public void setFiscalYear3 (String fiscalYear3) {
        this.fiscalYear3 = fiscalYear3;
    }

	@Column(name = "`FISCAL_YEAR_2`")
	private String fiscalYear2;

    public String getFiscalYear2 () {
        return this.fiscalYear2;
    }

    public void setFiscalYear2 (String fiscalYear2) {
        this.fiscalYear2 = fiscalYear2;
    }

	@Column(name = "`FISCAL_YEAR_1`")
	private String fiscalYear1;

    public String getFiscalYear1 () {
        return this.fiscalYear1;
    }

    public void setFiscalYear1 (String fiscalYear1) {
        this.fiscalYear1 = fiscalYear1;
    }

	@Column(name = "`ALERT`")
	private String alert;

    public String getAlert () {
        return this.alert;
    }

    public void setAlert (String alert) {
        this.alert = alert;
    }

	@Column(name = "`AUDIT_FREQUENCY`")
	private String auditFrequency;

    public String getAuditFrequency () {
        return this.auditFrequency;
    }

    public void setAuditFrequency (String auditFrequency) {
        this.auditFrequency = auditFrequency;
    }

	@Column(name = "`PROGRESS`")
	private String progress;

    public String getProgress () {
        return this.progress;
    }

    public void setProgress (String progress) {
        this.progress = progress;
    }

	@Column(name = "`SECONDARY_AUDITOR`")
	private String secondaryAuditor;

    public String getSecondaryAuditor () {
        return this.secondaryAuditor;
    }

    public void setSecondaryAuditor (String secondaryAuditor) {
        this.secondaryAuditor = secondaryAuditor;
    }

	@Column(name = "`PRIMARY_AUDITOR`")
	private String primaryAuditor;

    public String getPrimaryAuditor () {
        return this.primaryAuditor;
    }

    public void setPrimaryAuditor (String primaryAuditor) {
        this.primaryAuditor = primaryAuditor;
    }

	@Column(name = "`STATUS_DATE`")
	private Date statusDate;

    public Date getStatusDate () {
        return this.statusDate;
    }

    public void setStatusDate (Date statusDate) {
        this.statusDate = statusDate;
    }

	@Column(name = "`AUDIT_STATUS`")
	private String auditStatus;

    public String getAuditStatus () {
        return this.auditStatus;
    }

    public void setAuditStatus (String auditStatus) {
        this.auditStatus = auditStatus;
    }

	@Column(name = "`ORGANIZATION_CODE`")
	private String organizationCode;

    public String getOrganizationCode () {
        return this.organizationCode;
    }

    public void setOrganizationCode (String organizationCode) {
        this.organizationCode = organizationCode;
    }

	@Column(name = "`AUDIT_ID`")
	private Integer auditId;

    public Integer getAuditId () {
        return this.auditId;
    }

    public void setAuditId (Integer auditId) {
        this.auditId = auditId;
    }

}