
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`FINANCE`")
public class Finance implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

	@Column(name = "`PP_OPER_REV`")
	private Double ppOperRev;

    public Double getPpOperRev () {
        return this.ppOperRev;
    }

    public void setPpOperRev (Double ppOperRev) {
        this.ppOperRev = ppOperRev;
    }

	@Column(name = "`BOND_RED_MILL`")
	private Long bondRedMill;

    public Long getBondRedMill () {
        return this.bondRedMill;
    }

    public void setBondRedMill (Long bondRedMill) {
        this.bondRedMill = bondRedMill;
    }

	@Column(name = "`SB184_MILL`")
	private Double sb184Mill;

    public Double getSb184Mill () {
        return this.sb184Mill;
    }

    public void setSb184Mill (Double sb184Mill) {
        this.sb184Mill = sb184Mill;
    }

	@Column(name = "`OVERRIDE_MILL`")
	private Double overrideMill;

    public Double getOverrideMill () {
        return this.overrideMill;
    }

    public void setOverrideMill (Double overrideMill) {
        this.overrideMill = overrideMill;
    }

	@Column(name = "`OVERRIDE_AMT`")
	private Double overrideAmt;

    public Double getOverrideAmt () {
        return this.overrideAmt;
    }

    public void setOverrideAmt (Double overrideAmt) {
        this.overrideAmt = overrideAmt;
    }

	@Column(name = "`TAX_CREDIT`")
	private Double taxCredit;

    public Double getTaxCredit () {
        return this.taxCredit;
    }

    public void setTaxCredit (Double taxCredit) {
        this.taxCredit = taxCredit;
    }

	@Column(name = "`ABATEMENTS`")
	private Long abatements;

    public Long getAbatements () {
        return this.abatements;
    }

    public void setAbatements (Long abatements) {
        this.abatements = abatements;
    }

	@Column(name = "`OMMITTED_PROP`")
	private Double ommittedProp;

    public Double getOmmittedProp () {
        return this.ommittedProp;
    }

    public void setOmmittedProp (Double ommittedProp) {
        this.ommittedProp = ommittedProp;
    }

	@Column(name = "`POVERTY_COUNT`")
	private Long povertyCount;

    public Long getPovertyCount () {
        return this.povertyCount;
    }

    public void setPovertyCount (Long povertyCount) {
        this.povertyCount = povertyCount;
    }

	@Column(name = "`SMALL_ATTENDANCE`")
	private Long smallAttendance;

    public Long getSmallAttendance () {
        return this.smallAttendance;
    }

    public void setSmallAttendance (Long smallAttendance) {
        this.smallAttendance = smallAttendance;
    }

	@Column(name = "`LOW_INCOME_FUND`")
	private Double lowIncomeFund;

    public Double getLowIncomeFund () {
        return this.lowIncomeFund;
    }

    public void setLowIncomeFund (Double lowIncomeFund) {
        this.lowIncomeFund = lowIncomeFund;
    }

	@Column(name = "`RECISION`")
	private Double recision;

    public Double getRecision () {
        return this.recision;
    }

    public void setRecision (Double recision) {
        this.recision = recision;
    }

	@Column(name = "`ADA_MILL`")
	private Long adaMill;

    public Long getAdaMill () {
        return this.adaMill;
    }

    public void setAdaMill (Long adaMill) {
        this.adaMill = adaMill;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

}