
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`SE_MONTHLY`")
public class SeMonthly implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`District_Number`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`DATE_CHANGED`")
	private Date dateChanged;

    public Date getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (Date dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`JAN_FPC`")
	private Double janFpc;

    public Double getJanFpc () {
        return this.janFpc;
    }

    public void setJanFpc (Double janFpc) {
        this.janFpc = janFpc;
    }

	@Column(name = "`FEB_FPC`")
	private Double febFpc;

    public Double getFebFpc () {
        return this.febFpc;
    }

    public void setFebFpc (Double febFpc) {
        this.febFpc = febFpc;
    }

	@Column(name = "`MAR_FPC`")
	private Double marFpc;

    public Double getMarFpc () {
        return this.marFpc;
    }

    public void setMarFpc (Double marFpc) {
        this.marFpc = marFpc;
    }

	@Column(name = "`APR_FPC`")
	private Double aprFpc;

    public Double getAprFpc () {
        return this.aprFpc;
    }

    public void setAprFpc (Double aprFpc) {
        this.aprFpc = aprFpc;
    }

	@Column(name = "`MAY_FPC`")
	private Double mayFpc;

    public Double getMayFpc () {
        return this.mayFpc;
    }

    public void setMayFpc (Double mayFpc) {
        this.mayFpc = mayFpc;
    }

	@Column(name = "`JUN_FPC`")
	private Double junFpc;

    public Double getJunFpc () {
        return this.junFpc;
    }

    public void setJunFpc (Double junFpc) {
        this.junFpc = junFpc;
    }

	@Column(name = "`JUL_FPC`")
	private Double julFpc;

    public Double getJulFpc () {
        return this.julFpc;
    }

    public void setJulFpc (Double julFpc) {
        this.julFpc = julFpc;
    }

	@Column(name = "`AUG_FPC`")
	private Double augFpc;

    public Double getAugFpc () {
        return this.augFpc;
    }

    public void setAugFpc (Double augFpc) {
        this.augFpc = augFpc;
    }

	@Column(name = "`SEP_FPC`")
	private Double sepFpc;

    public Double getSepFpc () {
        return this.sepFpc;
    }

    public void setSepFpc (Double sepFpc) {
        this.sepFpc = sepFpc;
    }

	@Column(name = "`OCT_FPC`")
	private Double octFpc;

    public Double getOctFpc () {
        return this.octFpc;
    }

    public void setOctFpc (Double octFpc) {
        this.octFpc = octFpc;
    }

	@Column(name = "`NOV_FPC`")
	private Double novFpc;

    public Double getNovFpc () {
        return this.novFpc;
    }

    public void setNovFpc (Double novFpc) {
        this.novFpc = novFpc;
    }

	@Column(name = "`DEC_FPC`")
	private Double decFpc;

    public Double getDecFpc () {
        return this.decFpc;
    }

    public void setDecFpc (Double decFpc) {
        this.decFpc = decFpc;
    }

	@Column(name = "`JAN_LUNCH_1_8`")
	private Double janLunch18;

    public Double getJanLunch18 () {
        return this.janLunch18;
    }

    public void setJanLunch18 (Double janLunch18) {
        this.janLunch18 = janLunch18;
    }

	@Column(name = "`FEB_LUNCH_1_8`")
	private Double febLunch18;

    public Double getFebLunch18 () {
        return this.febLunch18;
    }

    public void setFebLunch18 (Double febLunch18) {
        this.febLunch18 = febLunch18;
    }

	@Column(name = "`MAR_LUNCH_1_8`")
	private Double marLunch18;

    public Double getMarLunch18 () {
        return this.marLunch18;
    }

    public void setMarLunch18 (Double marLunch18) {
        this.marLunch18 = marLunch18;
    }

	@Column(name = "`APR_LUNCH_1_8`")
	private Double aprLunch18;

    public Double getAprLunch18 () {
        return this.aprLunch18;
    }

    public void setAprLunch18 (Double aprLunch18) {
        this.aprLunch18 = aprLunch18;
    }

	@Column(name = "`MAY_LUNCH_1_8`")
	private Double mayLunch18;

    public Double getMayLunch18 () {
        return this.mayLunch18;
    }

    public void setMayLunch18 (Double mayLunch18) {
        this.mayLunch18 = mayLunch18;
    }

	@Column(name = "`JUN_LUNCH_1_8`")
	private Double junLunch18;

    public Double getJunLunch18 () {
        return this.junLunch18;
    }

    public void setJunLunch18 (Double junLunch18) {
        this.junLunch18 = junLunch18;
    }

	@Column(name = "`JUL_LUNCH_1_8`")
	private Double julLunch18;

    public Double getJulLunch18 () {
        return this.julLunch18;
    }

    public void setJulLunch18 (Double julLunch18) {
        this.julLunch18 = julLunch18;
    }

	@Column(name = "`AUG_LUNCH_1_8`")
	private Double augLunch18;

    public Double getAugLunch18 () {
        return this.augLunch18;
    }

    public void setAugLunch18 (Double augLunch18) {
        this.augLunch18 = augLunch18;
    }

	@Column(name = "`SEP_LUNCH_1_8`")
	private Double sepLunch18;

    public Double getSepLunch18 () {
        return this.sepLunch18;
    }

    public void setSepLunch18 (Double sepLunch18) {
        this.sepLunch18 = sepLunch18;
    }

	@Column(name = "`OCT_LUNCH_1_8`")
	private Double octLunch18;

    public Double getOctLunch18 () {
        return this.octLunch18;
    }

    public void setOctLunch18 (Double octLunch18) {
        this.octLunch18 = octLunch18;
    }

	@Column(name = "`NOV_LUNCH_1_8`")
	private Double novLunch18;

    public Double getNovLunch18 () {
        return this.novLunch18;
    }

    public void setNovLunch18 (Double novLunch18) {
        this.novLunch18 = novLunch18;
    }

	@Column(name = "`DEC_LUNCH_1_8`")
	private Double decLunch18;

    public Double getDecLunch18 () {
        return this.decLunch18;
    }

    public void setDecLunch18 (Double decLunch18) {
        this.decLunch18 = decLunch18;
    }

	@Column(name = "`JAN_LUNCH_K_12`")
	private Double janLunchK12;

    public Double getJanLunchK12 () {
        return this.janLunchK12;
    }

    public void setJanLunchK12 (Double janLunchK12) {
        this.janLunchK12 = janLunchK12;
    }

	@Column(name = "`FEB_LUNCH_K_12`")
	private Double febLunchK12;

    public Double getFebLunchK12 () {
        return this.febLunchK12;
    }

    public void setFebLunchK12 (Double febLunchK12) {
        this.febLunchK12 = febLunchK12;
    }

	@Column(name = "`MAR_LUNCH_K_12`")
	private Double marLunchK12;

    public Double getMarLunchK12 () {
        return this.marLunchK12;
    }

    public void setMarLunchK12 (Double marLunchK12) {
        this.marLunchK12 = marLunchK12;
    }

	@Column(name = "`APR_LUNCH_K_12`")
	private Double aprLunchK12;

    public Double getAprLunchK12 () {
        return this.aprLunchK12;
    }

    public void setAprLunchK12 (Double aprLunchK12) {
        this.aprLunchK12 = aprLunchK12;
    }

	@Column(name = "`MAY_LUNCH_K_12`")
	private Double mayLunchK12;

    public Double getMayLunchK12 () {
        return this.mayLunchK12;
    }

    public void setMayLunchK12 (Double mayLunchK12) {
        this.mayLunchK12 = mayLunchK12;
    }

	@Column(name = "`JUN_LUNCH_K_12`")
	private Double junLunchK12;

    public Double getJunLunchK12 () {
        return this.junLunchK12;
    }

    public void setJunLunchK12 (Double junLunchK12) {
        this.junLunchK12 = junLunchK12;
    }

	@Column(name = "`JUL_LUNCH_K_12`")
	private Double julLunchK12;

    public Double getJulLunchK12 () {
        return this.julLunchK12;
    }

    public void setJulLunchK12 (Double julLunchK12) {
        this.julLunchK12 = julLunchK12;
    }

	@Column(name = "`AUG_LUNCH_K_12`")
	private Double augLunchK12;

    public Double getAugLunchK12 () {
        return this.augLunchK12;
    }

    public void setAugLunchK12 (Double augLunchK12) {
        this.augLunchK12 = augLunchK12;
    }

	@Column(name = "`SEP_LUNCH_K_12`")
	private Double sepLunchK12;

    public Double getSepLunchK12 () {
        return this.sepLunchK12;
    }

    public void setSepLunchK12 (Double sepLunchK12) {
        this.sepLunchK12 = sepLunchK12;
    }

	@Column(name = "`OCT_LUNCH_K_12`")
	private Double octLunchK12;

    public Double getOctLunchK12 () {
        return this.octLunchK12;
    }

    public void setOctLunchK12 (Double octLunchK12) {
        this.octLunchK12 = octLunchK12;
    }

	@Column(name = "`NOV_LUNCH_K_12`")
	private Double novLunchK12;

    public Double getNovLunchK12 () {
        return this.novLunchK12;
    }

    public void setNovLunchK12 (Double novLunchK12) {
        this.novLunchK12 = novLunchK12;
    }

	@Column(name = "`DEC_LUNCH_K_12`")
	private Double decLunchK12;

    public Double getDecLunchK12 () {
        return this.decLunchK12;
    }

    public void setDecLunchK12 (Double decLunchK12) {
        this.decLunchK12 = decLunchK12;
    }

	@Column(name = "`JAN_SPEC_OWN_TAX`")
	private Double janSpecOwnTax;

    public Double getJanSpecOwnTax () {
        return this.janSpecOwnTax;
    }

    public void setJanSpecOwnTax (Double janSpecOwnTax) {
        this.janSpecOwnTax = janSpecOwnTax;
    }

	@Column(name = "`FEB_SPEC_OWN_TAX`")
	private Double febSpecOwnTax;

    public Double getFebSpecOwnTax () {
        return this.febSpecOwnTax;
    }

    public void setFebSpecOwnTax (Double febSpecOwnTax) {
        this.febSpecOwnTax = febSpecOwnTax;
    }

	@Column(name = "`MAR_SPEC_OWN_TAX`")
	private Double marSpecOwnTax;

    public Double getMarSpecOwnTax () {
        return this.marSpecOwnTax;
    }

    public void setMarSpecOwnTax (Double marSpecOwnTax) {
        this.marSpecOwnTax = marSpecOwnTax;
    }

	@Column(name = "`APR_SPEC_OWN_TAX`")
	private Double aprSpecOwnTax;

    public Double getAprSpecOwnTax () {
        return this.aprSpecOwnTax;
    }

    public void setAprSpecOwnTax (Double aprSpecOwnTax) {
        this.aprSpecOwnTax = aprSpecOwnTax;
    }

	@Column(name = "`MAY_SPEC_OWN_TAX`")
	private Double maySpecOwnTax;

    public Double getMaySpecOwnTax () {
        return this.maySpecOwnTax;
    }

    public void setMaySpecOwnTax (Double maySpecOwnTax) {
        this.maySpecOwnTax = maySpecOwnTax;
    }

	@Column(name = "`JUN_SPEC_OWN_TAX`")
	private Double junSpecOwnTax;

    public Double getJunSpecOwnTax () {
        return this.junSpecOwnTax;
    }

    public void setJunSpecOwnTax (Double junSpecOwnTax) {
        this.junSpecOwnTax = junSpecOwnTax;
    }

	@Column(name = "`JUL_SPEC_OWN_TAX`")
	private Double julSpecOwnTax;

    public Double getJulSpecOwnTax () {
        return this.julSpecOwnTax;
    }

    public void setJulSpecOwnTax (Double julSpecOwnTax) {
        this.julSpecOwnTax = julSpecOwnTax;
    }

	@Column(name = "`AUG_SPEC_OWN_TAX`")
	private Double augSpecOwnTax;

    public Double getAugSpecOwnTax () {
        return this.augSpecOwnTax;
    }

    public void setAugSpecOwnTax (Double augSpecOwnTax) {
        this.augSpecOwnTax = augSpecOwnTax;
    }

	@Column(name = "`SEP_SPEC_OWN_TAX`")
	private Double sepSpecOwnTax;

    public Double getSepSpecOwnTax () {
        return this.sepSpecOwnTax;
    }

    public void setSepSpecOwnTax (Double sepSpecOwnTax) {
        this.sepSpecOwnTax = sepSpecOwnTax;
    }

	@Column(name = "`OCT_SPEC_OWN_TAX`")
	private Double octSpecOwnTax;

    public Double getOctSpecOwnTax () {
        return this.octSpecOwnTax;
    }

    public void setOctSpecOwnTax (Double octSpecOwnTax) {
        this.octSpecOwnTax = octSpecOwnTax;
    }

	@Column(name = "`NOV_SPEC_OWN_TAX`")
	private Double novSpecOwnTax;

    public Double getNovSpecOwnTax () {
        return this.novSpecOwnTax;
    }

    public void setNovSpecOwnTax (Double novSpecOwnTax) {
        this.novSpecOwnTax = novSpecOwnTax;
    }

	@Column(name = "`DEC_SPEC_OWN_TAX`")
	private Double decSpecOwnTax;

    public Double getDecSpecOwnTax () {
        return this.decSpecOwnTax;
    }

    public void setDecSpecOwnTax (Double decSpecOwnTax) {
        this.decSpecOwnTax = decSpecOwnTax;
    }

	@Column(name = "`JAN_ASSESSED_VAL`")
	private Double janAssessedVal;

    public Double getJanAssessedVal () {
        return this.janAssessedVal;
    }

    public void setJanAssessedVal (Double janAssessedVal) {
        this.janAssessedVal = janAssessedVal;
    }

	@Column(name = "`FEB_ASSESSED_VAL`")
	private Double febAssessedVal;

    public Double getFebAssessedVal () {
        return this.febAssessedVal;
    }

    public void setFebAssessedVal (Double febAssessedVal) {
        this.febAssessedVal = febAssessedVal;
    }

	@Column(name = "`MAR_ASSESSED_VAL`")
	private Double marAssessedVal;

    public Double getMarAssessedVal () {
        return this.marAssessedVal;
    }

    public void setMarAssessedVal (Double marAssessedVal) {
        this.marAssessedVal = marAssessedVal;
    }

	@Column(name = "`APR_ASSESSED_VAL`")
	private Double aprAssessedVal;

    public Double getAprAssessedVal () {
        return this.aprAssessedVal;
    }

    public void setAprAssessedVal (Double aprAssessedVal) {
        this.aprAssessedVal = aprAssessedVal;
    }

	@Column(name = "`MAY_ASSESSED_VAL`")
	private Double mayAssessedVal;

    public Double getMayAssessedVal () {
        return this.mayAssessedVal;
    }

    public void setMayAssessedVal (Double mayAssessedVal) {
        this.mayAssessedVal = mayAssessedVal;
    }

	@Column(name = "`JUN_ASSESSED_VAL`")
	private Double junAssessedVal;

    public Double getJunAssessedVal () {
        return this.junAssessedVal;
    }

    public void setJunAssessedVal (Double junAssessedVal) {
        this.junAssessedVal = junAssessedVal;
    }

	@Column(name = "`JUL_ASSESSED_VAL`")
	private Double julAssessedVal;

    public Double getJulAssessedVal () {
        return this.julAssessedVal;
    }

    public void setJulAssessedVal (Double julAssessedVal) {
        this.julAssessedVal = julAssessedVal;
    }

	@Column(name = "`AUG_ASSESSED_VAL`")
	private Double augAssessedVal;

    public Double getAugAssessedVal () {
        return this.augAssessedVal;
    }

    public void setAugAssessedVal (Double augAssessedVal) {
        this.augAssessedVal = augAssessedVal;
    }

	@Column(name = "`SEP_ASSESSED_VAL`")
	private Double sepAssessedVal;

    public Double getSepAssessedVal () {
        return this.sepAssessedVal;
    }

    public void setSepAssessedVal (Double sepAssessedVal) {
        this.sepAssessedVal = sepAssessedVal;
    }

	@Column(name = "`OCT_ASSESSED_VAL`")
	private Double octAssessedVal;

    public Double getOctAssessedVal () {
        return this.octAssessedVal;
    }

    public void setOctAssessedVal (Double octAssessedVal) {
        this.octAssessedVal = octAssessedVal;
    }

	@Column(name = "`NOV_ASSESSED_VAL`")
	private Double novAssessedVal;

    public Double getNovAssessedVal () {
        return this.novAssessedVal;
    }

    public void setNovAssessedVal (Double novAssessedVal) {
        this.novAssessedVal = novAssessedVal;
    }

	@Column(name = "`DEC_ASSESSED_VAL`")
	private Double decAssessedVal;

    public Double getDecAssessedVal () {
        return this.decAssessedVal;
    }

    public void setDecAssessedVal (Double decAssessedVal) {
        this.decAssessedVal = decAssessedVal;
    }

	@Column(name = "`JAN_TOTAL_CATS`")
	private Double janTotalCats;

    public Double getJanTotalCats () {
        return this.janTotalCats;
    }

    public void setJanTotalCats (Double janTotalCats) {
        this.janTotalCats = janTotalCats;
    }

	@Column(name = "`FEB_TOTAL_CATS`")
	private Double febTotalCats;

    public Double getFebTotalCats () {
        return this.febTotalCats;
    }

    public void setFebTotalCats (Double febTotalCats) {
        this.febTotalCats = febTotalCats;
    }

	@Column(name = "`MAR_TOTAL_CATS`")
	private Double marTotalCats;

    public Double getMarTotalCats () {
        return this.marTotalCats;
    }

    public void setMarTotalCats (Double marTotalCats) {
        this.marTotalCats = marTotalCats;
    }

	@Column(name = "`APR_TOTAL_CATS`")
	private Double aprTotalCats;

    public Double getAprTotalCats () {
        return this.aprTotalCats;
    }

    public void setAprTotalCats (Double aprTotalCats) {
        this.aprTotalCats = aprTotalCats;
    }

	@Column(name = "`MAY_TOTAL_CATS`")
	private Double mayTotalCats;

    public Double getMayTotalCats () {
        return this.mayTotalCats;
    }

    public void setMayTotalCats (Double mayTotalCats) {
        this.mayTotalCats = mayTotalCats;
    }

	@Column(name = "`JUN_TOTAL_CATS`")
	private Double junTotalCats;

    public Double getJunTotalCats () {
        return this.junTotalCats;
    }

    public void setJunTotalCats (Double junTotalCats) {
        this.junTotalCats = junTotalCats;
    }

	@Column(name = "`JUL_TOTAL_CATS`")
	private Double julTotalCats;

    public Double getJulTotalCats () {
        return this.julTotalCats;
    }

    public void setJulTotalCats (Double julTotalCats) {
        this.julTotalCats = julTotalCats;
    }

	@Column(name = "`AUG_TOTAL_CATS`")
	private Double augTotalCats;

    public Double getAugTotalCats () {
        return this.augTotalCats;
    }

    public void setAugTotalCats (Double augTotalCats) {
        this.augTotalCats = augTotalCats;
    }

	@Column(name = "`SEP_TOTAL_CATS`")
	private Double sepTotalCats;

    public Double getSepTotalCats () {
        return this.sepTotalCats;
    }

    public void setSepTotalCats (Double sepTotalCats) {
        this.sepTotalCats = sepTotalCats;
    }

	@Column(name = "`OCT_TOTAL_CATS`")
	private Double octTotalCats;

    public Double getOctTotalCats () {
        return this.octTotalCats;
    }

    public void setOctTotalCats (Double octTotalCats) {
        this.octTotalCats = octTotalCats;
    }

	@Column(name = "`NOV_TOTAL_CATS`")
	private Double novTotalCats;

    public Double getNovTotalCats () {
        return this.novTotalCats;
    }

    public void setNovTotalCats (Double novTotalCats) {
        this.novTotalCats = novTotalCats;
    }

	@Column(name = "`DEC_TOTAL_CATS`")
	private Double decTotalCats;

    public Double getDecTotalCats () {
        return this.decTotalCats;
    }

    public void setDecTotalCats (Double decTotalCats) {
        this.decTotalCats = decTotalCats;
    }

	@Column(name = "`JAN_TOT_FUND_TP3`")
	private Double janTotFundTp3;

    public Double getJanTotFundTp3 () {
        return this.janTotFundTp3;
    }

    public void setJanTotFundTp3 (Double janTotFundTp3) {
        this.janTotFundTp3 = janTotFundTp3;
    }

	@Column(name = "`FEB_TOT_FUND_TP3`")
	private Double febTotFundTp3;

    public Double getFebTotFundTp3 () {
        return this.febTotFundTp3;
    }

    public void setFebTotFundTp3 (Double febTotFundTp3) {
        this.febTotFundTp3 = febTotFundTp3;
    }

	@Column(name = "`MAR_TOT_FUND_TP3`")
	private Double marTotFundTp3;

    public Double getMarTotFundTp3 () {
        return this.marTotFundTp3;
    }

    public void setMarTotFundTp3 (Double marTotFundTp3) {
        this.marTotFundTp3 = marTotFundTp3;
    }

	@Column(name = "`APR_TOT_FUND_TP3`")
	private Double aprTotFundTp3;

    public Double getAprTotFundTp3 () {
        return this.aprTotFundTp3;
    }

    public void setAprTotFundTp3 (Double aprTotFundTp3) {
        this.aprTotFundTp3 = aprTotFundTp3;
    }

	@Column(name = "`MAY_TOT_FUND_TP3`")
	private Double mayTotFundTp3;

    public Double getMayTotFundTp3 () {
        return this.mayTotFundTp3;
    }

    public void setMayTotFundTp3 (Double mayTotFundTp3) {
        this.mayTotFundTp3 = mayTotFundTp3;
    }

	@Column(name = "`JUN_TOT_FUND_TP3`")
	private Double junTotFundTp3;

    public Double getJunTotFundTp3 () {
        return this.junTotFundTp3;
    }

    public void setJunTotFundTp3 (Double junTotFundTp3) {
        this.junTotFundTp3 = junTotFundTp3;
    }

	@Column(name = "`JUL_TOT_FUND_TP3`")
	private Double julTotFundTp3;

    public Double getJulTotFundTp3 () {
        return this.julTotFundTp3;
    }

    public void setJulTotFundTp3 (Double julTotFundTp3) {
        this.julTotFundTp3 = julTotFundTp3;
    }

	@Column(name = "`AUG_TOT_FUND_TP3`")
	private Double augTotFundTp3;

    public Double getAugTotFundTp3 () {
        return this.augTotFundTp3;
    }

    public void setAugTotFundTp3 (Double augTotFundTp3) {
        this.augTotFundTp3 = augTotFundTp3;
    }

	@Column(name = "`SEP_TOT_FUND_TP3`")
	private Double sepTotFundTp3;

    public Double getSepTotFundTp3 () {
        return this.sepTotFundTp3;
    }

    public void setSepTotFundTp3 (Double sepTotFundTp3) {
        this.sepTotFundTp3 = sepTotFundTp3;
    }

	@Column(name = "`OCT_TOT_FUND_TP3`")
	private Double octTotFundTp3;

    public Double getOctTotFundTp3 () {
        return this.octTotFundTp3;
    }

    public void setOctTotFundTp3 (Double octTotFundTp3) {
        this.octTotFundTp3 = octTotFundTp3;
    }

	@Column(name = "`NOV_TOT_FUND_TP3`")
	private Double novTotFundTp3;

    public Double getNovTotFundTp3 () {
        return this.novTotFundTp3;
    }

    public void setNovTotFundTp3 (Double novTotFundTp3) {
        this.novTotFundTp3 = novTotFundTp3;
    }

	@Column(name = "`DEC_TOT_FUND_TP3`")
	private Double decTotFundTp3;

    public Double getDecTotFundTp3 () {
        return this.decTotFundTp3;
    }

    public void setDecTotFundTp3 (Double decTotFundTp3) {
        this.decTotFundTp3 = decTotFundTp3;
    }

	@Column(name = "`JAN_STATE_EQUAL_OWNER`")
	private Double janStateEqualOwner;

    public Double getJanStateEqualOwner () {
        return this.janStateEqualOwner;
    }

    public void setJanStateEqualOwner (Double janStateEqualOwner) {
        this.janStateEqualOwner = janStateEqualOwner;
    }

	@Column(name = "`FEB_STATE_EQUAL_OWNER`")
	private Double febStateEqualOwner;

    public Double getFebStateEqualOwner () {
        return this.febStateEqualOwner;
    }

    public void setFebStateEqualOwner (Double febStateEqualOwner) {
        this.febStateEqualOwner = febStateEqualOwner;
    }

	@Column(name = "`MAR_STATE_EQUAL_OWNER`")
	private Double marStateEqualOwner;

    public Double getMarStateEqualOwner () {
        return this.marStateEqualOwner;
    }

    public void setMarStateEqualOwner (Double marStateEqualOwner) {
        this.marStateEqualOwner = marStateEqualOwner;
    }

	@Column(name = "`APR_STATE_EQUAL_OWNER`")
	private Double aprStateEqualOwner;

    public Double getAprStateEqualOwner () {
        return this.aprStateEqualOwner;
    }

    public void setAprStateEqualOwner (Double aprStateEqualOwner) {
        this.aprStateEqualOwner = aprStateEqualOwner;
    }

	@Column(name = "`MAY_STATE_EQUAL_OWNER`")
	private Double mayStateEqualOwner;

    public Double getMayStateEqualOwner () {
        return this.mayStateEqualOwner;
    }

    public void setMayStateEqualOwner (Double mayStateEqualOwner) {
        this.mayStateEqualOwner = mayStateEqualOwner;
    }

	@Column(name = "`JUN_STATE_EQUAL_OWNER`")
	private Double junStateEqualOwner;

    public Double getJunStateEqualOwner () {
        return this.junStateEqualOwner;
    }

    public void setJunStateEqualOwner (Double junStateEqualOwner) {
        this.junStateEqualOwner = junStateEqualOwner;
    }

	@Column(name = "`JUL_STATE_EQUAL_OWNER`")
	private Double julStateEqualOwner;

    public Double getJulStateEqualOwner () {
        return this.julStateEqualOwner;
    }

    public void setJulStateEqualOwner (Double julStateEqualOwner) {
        this.julStateEqualOwner = julStateEqualOwner;
    }

	@Column(name = "`AUG_STATE_EQUAL_OWNER`")
	private Double augStateEqualOwner;

    public Double getAugStateEqualOwner () {
        return this.augStateEqualOwner;
    }

    public void setAugStateEqualOwner (Double augStateEqualOwner) {
        this.augStateEqualOwner = augStateEqualOwner;
    }

	@Column(name = "`SEP_STATE_EQUAL_OWNER`")
	private Double sepStateEqualOwner;

    public Double getSepStateEqualOwner () {
        return this.sepStateEqualOwner;
    }

    public void setSepStateEqualOwner (Double sepStateEqualOwner) {
        this.sepStateEqualOwner = sepStateEqualOwner;
    }

	@Column(name = "`OCT_STATE_EQUAL_OWNER`")
	private Double octStateEqualOwner;

    public Double getOctStateEqualOwner () {
        return this.octStateEqualOwner;
    }

    public void setOctStateEqualOwner (Double octStateEqualOwner) {
        this.octStateEqualOwner = octStateEqualOwner;
    }

	@Column(name = "`NOV_STATE_EQUAL_OWNER`")
	private Double novStateEqualOwner;

    public Double getNovStateEqualOwner () {
        return this.novStateEqualOwner;
    }

    public void setNovStateEqualOwner (Double novStateEqualOwner) {
        this.novStateEqualOwner = novStateEqualOwner;
    }

	@Column(name = "`DEC_STATE_EQUAL_OWNER`")
	private Double decStateEqualOwner;

    public Double getDecStateEqualOwner () {
        return this.decStateEqualOwner;
    }

    public void setDecStateEqualOwner (Double decStateEqualOwner) {
        this.decStateEqualOwner = decStateEqualOwner;
    }

	@Column(name = "`JAN_MILL_LEVY`")
	private Double janMillLevy;

    public Double getJanMillLevy () {
        return this.janMillLevy;
    }

    public void setJanMillLevy (Double janMillLevy) {
        this.janMillLevy = janMillLevy;
    }

	@Column(name = "`FEB_MILL_LEVY`")
	private Double febMillLevy;

    public Double getFebMillLevy () {
        return this.febMillLevy;
    }

    public void setFebMillLevy (Double febMillLevy) {
        this.febMillLevy = febMillLevy;
    }

	@Column(name = "`MAR_MILL_LEVY`")
	private Double marMillLevy;

    public Double getMarMillLevy () {
        return this.marMillLevy;
    }

    public void setMarMillLevy (Double marMillLevy) {
        this.marMillLevy = marMillLevy;
    }

	@Column(name = "`APR_MILL_LEVY`")
	private Double aprMillLevy;

    public Double getAprMillLevy () {
        return this.aprMillLevy;
    }

    public void setAprMillLevy (Double aprMillLevy) {
        this.aprMillLevy = aprMillLevy;
    }

	@Column(name = "`MAY_MILL_LEVY`")
	private Double mayMillLevy;

    public Double getMayMillLevy () {
        return this.mayMillLevy;
    }

    public void setMayMillLevy (Double mayMillLevy) {
        this.mayMillLevy = mayMillLevy;
    }

	@Column(name = "`JUN_MILL_LEVY`")
	private Double junMillLevy;

    public Double getJunMillLevy () {
        return this.junMillLevy;
    }

    public void setJunMillLevy (Double junMillLevy) {
        this.junMillLevy = junMillLevy;
    }

	@Column(name = "`JUL_MILL_LEVY`")
	private Double julMillLevy;

    public Double getJulMillLevy () {
        return this.julMillLevy;
    }

    public void setJulMillLevy (Double julMillLevy) {
        this.julMillLevy = julMillLevy;
    }

	@Column(name = "`AUG_MILL_LEVY`")
	private Double augMillLevy;

    public Double getAugMillLevy () {
        return this.augMillLevy;
    }

    public void setAugMillLevy (Double augMillLevy) {
        this.augMillLevy = augMillLevy;
    }

	@Column(name = "`SEP_MILL_LEVY`")
	private Double sepMillLevy;

    public Double getSepMillLevy () {
        return this.sepMillLevy;
    }

    public void setSepMillLevy (Double sepMillLevy) {
        this.sepMillLevy = sepMillLevy;
    }

	@Column(name = "`OCT_MILL_LEVY`")
	private Double octMillLevy;

    public Double getOctMillLevy () {
        return this.octMillLevy;
    }

    public void setOctMillLevy (Double octMillLevy) {
        this.octMillLevy = octMillLevy;
    }

	@Column(name = "`NOV_MILL_LEVY`")
	private Double novMillLevy;

    public Double getNovMillLevy () {
        return this.novMillLevy;
    }

    public void setNovMillLevy (Double novMillLevy) {
        this.novMillLevy = novMillLevy;
    }

	@Column(name = "`DEC_MILL_LEVY`")
	private Double decMillLevy;

    public Double getDecMillLevy () {
        return this.decMillLevy;
    }

    public void setDecMillLevy (Double decMillLevy) {
        this.decMillLevy = decMillLevy;
    }

	@Column(name = "`JAN_CAT_ML_LEVY`")
	private Double janCatMlLevy;

    public Double getJanCatMlLevy () {
        return this.janCatMlLevy;
    }

    public void setJanCatMlLevy (Double janCatMlLevy) {
        this.janCatMlLevy = janCatMlLevy;
    }

	@Column(name = "`FEB_CAT_ML_LEVY`")
	private Double febCatMlLevy;

    public Double getFebCatMlLevy () {
        return this.febCatMlLevy;
    }

    public void setFebCatMlLevy (Double febCatMlLevy) {
        this.febCatMlLevy = febCatMlLevy;
    }

	@Column(name = "`MAR_CAT_ML_LEVY`")
	private Double marCatMlLevy;

    public Double getMarCatMlLevy () {
        return this.marCatMlLevy;
    }

    public void setMarCatMlLevy (Double marCatMlLevy) {
        this.marCatMlLevy = marCatMlLevy;
    }

	@Column(name = "`APR_CAT_ML_LEVY`")
	private Double aprCatMlLevy;

    public Double getAprCatMlLevy () {
        return this.aprCatMlLevy;
    }

    public void setAprCatMlLevy (Double aprCatMlLevy) {
        this.aprCatMlLevy = aprCatMlLevy;
    }

	@Column(name = "`MAY_CAT_ML_LEVY`")
	private Double mayCatMlLevy;

    public Double getMayCatMlLevy () {
        return this.mayCatMlLevy;
    }

    public void setMayCatMlLevy (Double mayCatMlLevy) {
        this.mayCatMlLevy = mayCatMlLevy;
    }

	@Column(name = "`JUN_CAT_ML_LEVY`")
	private Double junCatMlLevy;

    public Double getJunCatMlLevy () {
        return this.junCatMlLevy;
    }

    public void setJunCatMlLevy (Double junCatMlLevy) {
        this.junCatMlLevy = junCatMlLevy;
    }

	@Column(name = "`JUL_CAT_ML_LEVY`")
	private Double julCatMlLevy;

    public Double getJulCatMlLevy () {
        return this.julCatMlLevy;
    }

    public void setJulCatMlLevy (Double julCatMlLevy) {
        this.julCatMlLevy = julCatMlLevy;
    }

	@Column(name = "`AUG_CAT_ML_LEVY`")
	private Double augCatMlLevy;

    public Double getAugCatMlLevy () {
        return this.augCatMlLevy;
    }

    public void setAugCatMlLevy (Double augCatMlLevy) {
        this.augCatMlLevy = augCatMlLevy;
    }

	@Column(name = "`SEP_CAT_ML_LEVY`")
	private Double sepCatMlLevy;

    public Double getSepCatMlLevy () {
        return this.sepCatMlLevy;
    }

    public void setSepCatMlLevy (Double sepCatMlLevy) {
        this.sepCatMlLevy = sepCatMlLevy;
    }

	@Column(name = "`OCT_CAT_ML_LEVY`")
	private Double octCatMlLevy;

    public Double getOctCatMlLevy () {
        return this.octCatMlLevy;
    }

    public void setOctCatMlLevy (Double octCatMlLevy) {
        this.octCatMlLevy = octCatMlLevy;
    }

	@Column(name = "`NOV_CAT_ML_LEVY`")
	private Double novCatMlLevy;

    public Double getNovCatMlLevy () {
        return this.novCatMlLevy;
    }

    public void setNovCatMlLevy (Double novCatMlLevy) {
        this.novCatMlLevy = novCatMlLevy;
    }

	@Column(name = "`DEC_CAT_ML_LEVY`")
	private Double decCatMlLevy;

    public Double getDecCatMlLevy () {
        return this.decCatMlLevy;
    }

    public void setDecCatMlLevy (Double decCatMlLevy) {
        this.decCatMlLevy = decCatMlLevy;
    }

	@Column(name = "`JAN_MM_ENTITLE`")
	private Double janMmEntitle;

    public Double getJanMmEntitle () {
        return this.janMmEntitle;
    }

    public void setJanMmEntitle (Double janMmEntitle) {
        this.janMmEntitle = janMmEntitle;
    }

	@Column(name = "`FEB_MM_ENTITLE`")
	private Double febMmEntitle;

    public Double getFebMmEntitle () {
        return this.febMmEntitle;
    }

    public void setFebMmEntitle (Double febMmEntitle) {
        this.febMmEntitle = febMmEntitle;
    }

	@Column(name = "`MAR_MM_ENTITLE`")
	private Double marMmEntitle;

    public Double getMarMmEntitle () {
        return this.marMmEntitle;
    }

    public void setMarMmEntitle (Double marMmEntitle) {
        this.marMmEntitle = marMmEntitle;
    }

	@Column(name = "`APR_MM_ENTITLE`")
	private Double aprMmEntitle;

    public Double getAprMmEntitle () {
        return this.aprMmEntitle;
    }

    public void setAprMmEntitle (Double aprMmEntitle) {
        this.aprMmEntitle = aprMmEntitle;
    }

	@Column(name = "`MAY_MM_ENTITLE`")
	private Double mayMmEntitle;

    public Double getMayMmEntitle () {
        return this.mayMmEntitle;
    }

    public void setMayMmEntitle (Double mayMmEntitle) {
        this.mayMmEntitle = mayMmEntitle;
    }

	@Column(name = "`JUN_MM_ENTITLE`")
	private Double junMmEntitle;

    public Double getJunMmEntitle () {
        return this.junMmEntitle;
    }

    public void setJunMmEntitle (Double junMmEntitle) {
        this.junMmEntitle = junMmEntitle;
    }

	@Column(name = "`JUL_MM_ENTITLE`")
	private Double julMmEntitle;

    public Double getJulMmEntitle () {
        return this.julMmEntitle;
    }

    public void setJulMmEntitle (Double julMmEntitle) {
        this.julMmEntitle = julMmEntitle;
    }

	@Column(name = "`AUG_MM_ENTITLE`")
	private Double augMmEntitle;

    public Double getAugMmEntitle () {
        return this.augMmEntitle;
    }

    public void setAugMmEntitle (Double augMmEntitle) {
        this.augMmEntitle = augMmEntitle;
    }

	@Column(name = "`SEP_MM_ENTITLE`")
	private Double sepMmEntitle;

    public Double getSepMmEntitle () {
        return this.sepMmEntitle;
    }

    public void setSepMmEntitle (Double sepMmEntitle) {
        this.sepMmEntitle = sepMmEntitle;
    }

	@Column(name = "`OCT_MM_ENTITLE`")
	private Double octMmEntitle;

    public Double getOctMmEntitle () {
        return this.octMmEntitle;
    }

    public void setOctMmEntitle (Double octMmEntitle) {
        this.octMmEntitle = octMmEntitle;
    }

	@Column(name = "`NOV_MM_ENTITLE`")
	private Double novMmEntitle;

    public Double getNovMmEntitle () {
        return this.novMmEntitle;
    }

    public void setNovMmEntitle (Double novMmEntitle) {
        this.novMmEntitle = novMmEntitle;
    }

	@Column(name = "`DEC_MM_ENTITLE`")
	private Double decMmEntitle;

    public Double getDecMmEntitle () {
        return this.decMmEntitle;
    }

    public void setDecMmEntitle (Double decMmEntitle) {
        this.decMmEntitle = decMmEntitle;
    }

	@Column(name = "`DEC_ACT_ENTITLE`")
	private Double decActEntitle;

    public Double getDecActEntitle () {
        return this.decActEntitle;
    }

    public void setDecActEntitle (Double decActEntitle) {
        this.decActEntitle = decActEntitle;
    }

	@Column(name = "`JUN_ACT_ENTITLE`")
	private Double junActEntitle;

    public Double getJunActEntitle () {
        return this.junActEntitle;
    }

    public void setJunActEntitle (Double junActEntitle) {
        this.junActEntitle = junActEntitle;
    }

	@Column(name = "`JAN_MM_OODS_ADJ`")
	private Double janMmOodsAdj;

    public Double getJanMmOodsAdj () {
        return this.janMmOodsAdj;
    }

    public void setJanMmOodsAdj (Double janMmOodsAdj) {
        this.janMmOodsAdj = janMmOodsAdj;
    }

	@Column(name = "`FEB_MM_OODS_ADJ`")
	private Double febMmOodsAdj;

    public Double getFebMmOodsAdj () {
        return this.febMmOodsAdj;
    }

    public void setFebMmOodsAdj (Double febMmOodsAdj) {
        this.febMmOodsAdj = febMmOodsAdj;
    }

	@Column(name = "`MAR_MM_OODS_ADJ`")
	private Double marMmOodsAdj;

    public Double getMarMmOodsAdj () {
        return this.marMmOodsAdj;
    }

    public void setMarMmOodsAdj (Double marMmOodsAdj) {
        this.marMmOodsAdj = marMmOodsAdj;
    }

	@Column(name = "`APR_MM_OODS_ADJ`")
	private Double aprMmOodsAdj;

    public Double getAprMmOodsAdj () {
        return this.aprMmOodsAdj;
    }

    public void setAprMmOodsAdj (Double aprMmOodsAdj) {
        this.aprMmOodsAdj = aprMmOodsAdj;
    }

	@Column(name = "`MAY_MM_OODS_ADJ`")
	private Double mayMmOodsAdj;

    public Double getMayMmOodsAdj () {
        return this.mayMmOodsAdj;
    }

    public void setMayMmOodsAdj (Double mayMmOodsAdj) {
        this.mayMmOodsAdj = mayMmOodsAdj;
    }

	@Column(name = "`JUN_MM_OODS_ADJ`")
	private Double junMmOodsAdj;

    public Double getJunMmOodsAdj () {
        return this.junMmOodsAdj;
    }

    public void setJunMmOodsAdj (Double junMmOodsAdj) {
        this.junMmOodsAdj = junMmOodsAdj;
    }

	@Column(name = "`JUL_MM_OODS_ADJ`")
	private Double julMmOodsAdj;

    public Double getJulMmOodsAdj () {
        return this.julMmOodsAdj;
    }

    public void setJulMmOodsAdj (Double julMmOodsAdj) {
        this.julMmOodsAdj = julMmOodsAdj;
    }

	@Column(name = "`AUG_MM_OODS_ADJ`")
	private Double augMmOodsAdj;

    public Double getAugMmOodsAdj () {
        return this.augMmOodsAdj;
    }

    public void setAugMmOodsAdj (Double augMmOodsAdj) {
        this.augMmOodsAdj = augMmOodsAdj;
    }

	@Column(name = "`SEP_MM_OODS_ADJ`")
	private Double sepMmOodsAdj;

    public Double getSepMmOodsAdj () {
        return this.sepMmOodsAdj;
    }

    public void setSepMmOodsAdj (Double sepMmOodsAdj) {
        this.sepMmOodsAdj = sepMmOodsAdj;
    }

	@Column(name = "`OCT_MM_OODS_ADJ`")
	private Double octMmOodsAdj;

    public Double getOctMmOodsAdj () {
        return this.octMmOodsAdj;
    }

    public void setOctMmOodsAdj (Double octMmOodsAdj) {
        this.octMmOodsAdj = octMmOodsAdj;
    }

	@Column(name = "`NOV_MM_OODS_ADJ`")
	private Double novMmOodsAdj;

    public Double getNovMmOodsAdj () {
        return this.novMmOodsAdj;
    }

    public void setNovMmOodsAdj (Double novMmOodsAdj) {
        this.novMmOodsAdj = novMmOodsAdj;
    }

	@Column(name = "`DEC_MM_OODS_ADJ`")
	private Double decMmOodsAdj;

    public Double getDecMmOodsAdj () {
        return this.decMmOodsAdj;
    }

    public void setDecMmOodsAdj (Double decMmOodsAdj) {
        this.decMmOodsAdj = decMmOodsAdj;
    }

	@Column(name = "`JAN_MM_SWAP_ADJ`")
	private Double janMmSwapAdj;

    public Double getJanMmSwapAdj () {
        return this.janMmSwapAdj;
    }

    public void setJanMmSwapAdj (Double janMmSwapAdj) {
        this.janMmSwapAdj = janMmSwapAdj;
    }

	@Column(name = "`FEB_MM_SWAP_ADJ`")
	private Double febMmSwapAdj;

    public Double getFebMmSwapAdj () {
        return this.febMmSwapAdj;
    }

    public void setFebMmSwapAdj (Double febMmSwapAdj) {
        this.febMmSwapAdj = febMmSwapAdj;
    }

	@Column(name = "`MAR_MM_SWAP_ADJ`")
	private Double marMmSwapAdj;

    public Double getMarMmSwapAdj () {
        return this.marMmSwapAdj;
    }

    public void setMarMmSwapAdj (Double marMmSwapAdj) {
        this.marMmSwapAdj = marMmSwapAdj;
    }

	@Column(name = "`APR_MM_SWAP_ADJ`")
	private Double aprMmSwapAdj;

    public Double getAprMmSwapAdj () {
        return this.aprMmSwapAdj;
    }

    public void setAprMmSwapAdj (Double aprMmSwapAdj) {
        this.aprMmSwapAdj = aprMmSwapAdj;
    }

	@Column(name = "`MAY_MM_SWAP_ADJ`")
	private Double mayMmSwapAdj;

    public Double getMayMmSwapAdj () {
        return this.mayMmSwapAdj;
    }

    public void setMayMmSwapAdj (Double mayMmSwapAdj) {
        this.mayMmSwapAdj = mayMmSwapAdj;
    }

	@Column(name = "`JUN_MM_SWAP_ADJ`")
	private Double junMmSwapAdj;

    public Double getJunMmSwapAdj () {
        return this.junMmSwapAdj;
    }

    public void setJunMmSwapAdj (Double junMmSwapAdj) {
        this.junMmSwapAdj = junMmSwapAdj;
    }

	@Column(name = "`JUL_MM_SWAP_ADJ`")
	private Double julMmSwapAdj;

    public Double getJulMmSwapAdj () {
        return this.julMmSwapAdj;
    }

    public void setJulMmSwapAdj (Double julMmSwapAdj) {
        this.julMmSwapAdj = julMmSwapAdj;
    }

	@Column(name = "`AUG_MM_SWAP_ADJ`")
	private Double augMmSwapAdj;

    public Double getAugMmSwapAdj () {
        return this.augMmSwapAdj;
    }

    public void setAugMmSwapAdj (Double augMmSwapAdj) {
        this.augMmSwapAdj = augMmSwapAdj;
    }

	@Column(name = "`SEP_MM_SWAP_ADJ`")
	private Double sepMmSwapAdj;

    public Double getSepMmSwapAdj () {
        return this.sepMmSwapAdj;
    }

    public void setSepMmSwapAdj (Double sepMmSwapAdj) {
        this.sepMmSwapAdj = sepMmSwapAdj;
    }

	@Column(name = "`OCT_MM_SWAP_ADJ`")
	private Double octMmSwapAdj;

    public Double getOctMmSwapAdj () {
        return this.octMmSwapAdj;
    }

    public void setOctMmSwapAdj (Double octMmSwapAdj) {
        this.octMmSwapAdj = octMmSwapAdj;
    }

	@Column(name = "`NOV_MM_SWAP_ADJ`")
	private Double novMmSwapAdj;

    public Double getNovMmSwapAdj () {
        return this.novMmSwapAdj;
    }

    public void setNovMmSwapAdj (Double novMmSwapAdj) {
        this.novMmSwapAdj = novMmSwapAdj;
    }

	@Column(name = "`DEC_MM_SWAP_ADJ`")
	private Double decMmSwapAdj;

    public Double getDecMmSwapAdj () {
        return this.decMmSwapAdj;
    }

    public void setDecMmSwapAdj (Double decMmSwapAdj) {
        this.decMmSwapAdj = decMmSwapAdj;
    }

	@Column(name = "`JAN_MM_OTHER_ADJ`")
	private Double janMmOtherAdj;

    public Double getJanMmOtherAdj () {
        return this.janMmOtherAdj;
    }

    public void setJanMmOtherAdj (Double janMmOtherAdj) {
        this.janMmOtherAdj = janMmOtherAdj;
    }

	@Column(name = "`FEB_MM_OTHER_ADJ`")
	private Double febMmOtherAdj;

    public Double getFebMmOtherAdj () {
        return this.febMmOtherAdj;
    }

    public void setFebMmOtherAdj (Double febMmOtherAdj) {
        this.febMmOtherAdj = febMmOtherAdj;
    }

	@Column(name = "`MAR_MM_OTHER_ADJ`")
	private Double marMmOtherAdj;

    public Double getMarMmOtherAdj () {
        return this.marMmOtherAdj;
    }

    public void setMarMmOtherAdj (Double marMmOtherAdj) {
        this.marMmOtherAdj = marMmOtherAdj;
    }

	@Column(name = "`APR_MM_OTHER_ADJ`")
	private Double aprMmOtherAdj;

    public Double getAprMmOtherAdj () {
        return this.aprMmOtherAdj;
    }

    public void setAprMmOtherAdj (Double aprMmOtherAdj) {
        this.aprMmOtherAdj = aprMmOtherAdj;
    }

	@Column(name = "`MAY_MM_OTHER_ADJ`")
	private Double mayMmOtherAdj;

    public Double getMayMmOtherAdj () {
        return this.mayMmOtherAdj;
    }

    public void setMayMmOtherAdj (Double mayMmOtherAdj) {
        this.mayMmOtherAdj = mayMmOtherAdj;
    }

	@Column(name = "`JUN_MM_OTHER_ADJ`")
	private Double junMmOtherAdj;

    public Double getJunMmOtherAdj () {
        return this.junMmOtherAdj;
    }

    public void setJunMmOtherAdj (Double junMmOtherAdj) {
        this.junMmOtherAdj = junMmOtherAdj;
    }

	@Column(name = "`JUL_MM_OTHER_ADJ`")
	private Double julMmOtherAdj;

    public Double getJulMmOtherAdj () {
        return this.julMmOtherAdj;
    }

    public void setJulMmOtherAdj (Double julMmOtherAdj) {
        this.julMmOtherAdj = julMmOtherAdj;
    }

	@Column(name = "`AUG_MM_OTHER_ADJ`")
	private Double augMmOtherAdj;

    public Double getAugMmOtherAdj () {
        return this.augMmOtherAdj;
    }

    public void setAugMmOtherAdj (Double augMmOtherAdj) {
        this.augMmOtherAdj = augMmOtherAdj;
    }

	@Column(name = "`SEP_MM_OTHER_ADJ`")
	private Double sepMmOtherAdj;

    public Double getSepMmOtherAdj () {
        return this.sepMmOtherAdj;
    }

    public void setSepMmOtherAdj (Double sepMmOtherAdj) {
        this.sepMmOtherAdj = sepMmOtherAdj;
    }

	@Column(name = "`OCT_MM_OTHER_ADJ`")
	private Double octMmOtherAdj;

    public Double getOctMmOtherAdj () {
        return this.octMmOtherAdj;
    }

    public void setOctMmOtherAdj (Double octMmOtherAdj) {
        this.octMmOtherAdj = octMmOtherAdj;
    }

	@Column(name = "`NOV_MM_OTHER_ADJ`")
	private Double novMmOtherAdj;

    public Double getNovMmOtherAdj () {
        return this.novMmOtherAdj;
    }

    public void setNovMmOtherAdj (Double novMmOtherAdj) {
        this.novMmOtherAdj = novMmOtherAdj;
    }

	@Column(name = "`DEC_MM_OTHER_ADJ`")
	private Double decMmOtherAdj;

    public Double getDecMmOtherAdj () {
        return this.decMmOtherAdj;
    }

    public void setDecMmOtherAdj (Double decMmOtherAdj) {
        this.decMmOtherAdj = decMmOtherAdj;
    }

	@Column(name = "`JAN_PAYMENT`")
	private Double janPayment;

    public Double getJanPayment () {
        return this.janPayment;
    }

    public void setJanPayment (Double janPayment) {
        this.janPayment = janPayment;
    }

	@Column(name = "`FEB_PAYMENT`")
	private Double febPayment;

    public Double getFebPayment () {
        return this.febPayment;
    }

    public void setFebPayment (Double febPayment) {
        this.febPayment = febPayment;
    }

	@Column(name = "`MAR_PAYMENT`")
	private Double marPayment;

    public Double getMarPayment () {
        return this.marPayment;
    }

    public void setMarPayment (Double marPayment) {
        this.marPayment = marPayment;
    }

	@Column(name = "`APR_PAYMENT`")
	private Double aprPayment;

    public Double getAprPayment () {
        return this.aprPayment;
    }

    public void setAprPayment (Double aprPayment) {
        this.aprPayment = aprPayment;
    }

	@Column(name = "`MAY_PAYMENT`")
	private Double mayPayment;

    public Double getMayPayment () {
        return this.mayPayment;
    }

    public void setMayPayment (Double mayPayment) {
        this.mayPayment = mayPayment;
    }

	@Column(name = "`JUN_PAYMENT`")
	private Double junPayment;

    public Double getJunPayment () {
        return this.junPayment;
    }

    public void setJunPayment (Double junPayment) {
        this.junPayment = junPayment;
    }

	@Column(name = "`JUL_PAYMENT`")
	private Double julPayment;

    public Double getJulPayment () {
        return this.julPayment;
    }

    public void setJulPayment (Double julPayment) {
        this.julPayment = julPayment;
    }

	@Column(name = "`AUG_PAYMENT`")
	private Double augPayment;

    public Double getAugPayment () {
        return this.augPayment;
    }

    public void setAugPayment (Double augPayment) {
        this.augPayment = augPayment;
    }

	@Column(name = "`SEP_PAYMENT`")
	private Double sepPayment;

    public Double getSepPayment () {
        return this.sepPayment;
    }

    public void setSepPayment (Double sepPayment) {
        this.sepPayment = sepPayment;
    }

	@Column(name = "`OCT_PAYMENT`")
	private Double octPayment;

    public Double getOctPayment () {
        return this.octPayment;
    }

    public void setOctPayment (Double octPayment) {
        this.octPayment = octPayment;
    }

	@Column(name = "`NOV_PAYMENT`")
	private Double novPayment;

    public Double getNovPayment () {
        return this.novPayment;
    }

    public void setNovPayment (Double novPayment) {
        this.novPayment = novPayment;
    }

	@Column(name = "`DEC_PAYMENT`")
	private Double decPayment;

    public Double getDecPayment () {
        return this.decPayment;
    }

    public void setDecPayment (Double decPayment) {
        this.decPayment = decPayment;
    }

	@Column(name = "`DEC_VARIANCE_1`")
	private Double decVariance1;

    public Double getDecVariance1 () {
        return this.decVariance1;
    }

    public void setDecVariance1 (Double decVariance1) {
        this.decVariance1 = decVariance1;
    }

	@Column(name = "`DEC_VARIANCE_2`")
	private Double decVariance2;

    public Double getDecVariance2 () {
        return this.decVariance2;
    }

    public void setDecVariance2 (Double decVariance2) {
        this.decVariance2 = decVariance2;
    }

	@Column(name = "`DEC_VARIANCE_3`")
	private Double decVariance3;

    public Double getDecVariance3 () {
        return this.decVariance3;
    }

    public void setDecVariance3 (Double decVariance3) {
        this.decVariance3 = decVariance3;
    }

	@Column(name = "`JAN_VARIANCE_1`")
	private Double janVariance1;

    public Double getJanVariance1 () {
        return this.janVariance1;
    }

    public void setJanVariance1 (Double janVariance1) {
        this.janVariance1 = janVariance1;
    }

	@Column(name = "`JAN_VARIANCE_2`")
	private Double janVariance2;

    public Double getJanVariance2 () {
        return this.janVariance2;
    }

    public void setJanVariance2 (Double janVariance2) {
        this.janVariance2 = janVariance2;
    }

	@Column(name = "`JAN_VARIANCE_3`")
	private Double janVariance3;

    public Double getJanVariance3 () {
        return this.janVariance3;
    }

    public void setJanVariance3 (Double janVariance3) {
        this.janVariance3 = janVariance3;
    }

	@Column(name = "`JUN_VARIANCE_1`")
	private Double junVariance1;

    public Double getJunVariance1 () {
        return this.junVariance1;
    }

    public void setJunVariance1 (Double junVariance1) {
        this.junVariance1 = junVariance1;
    }

	@Column(name = "`JUN_VARIANCE_2`")
	private Double junVariance2;

    public Double getJunVariance2 () {
        return this.junVariance2;
    }

    public void setJunVariance2 (Double junVariance2) {
        this.junVariance2 = junVariance2;
    }

	@Column(name = "`JUN_VARIANCE_3`")
	private Double junVariance3;

    public Double getJunVariance3 () {
        return this.junVariance3;
    }

    public void setJunVariance3 (Double junVariance3) {
        this.junVariance3 = junVariance3;
    }

	@Column(name = "`JAN_STATE_ASSESS`")
	private Double janStateAssess;

    public Double getJanStateAssess () {
        return this.janStateAssess;
    }

    public void setJanStateAssess (Double janStateAssess) {
        this.janStateAssess = janStateAssess;
    }

	@Column(name = "`FEB_STATE_ASSESS`")
	private Double febStateAssess;

    public Double getFebStateAssess () {
        return this.febStateAssess;
    }

    public void setFebStateAssess (Double febStateAssess) {
        this.febStateAssess = febStateAssess;
    }

	@Column(name = "`MAR_STATE_ASSESS`")
	private Double marStateAssess;

    public Double getMarStateAssess () {
        return this.marStateAssess;
    }

    public void setMarStateAssess (Double marStateAssess) {
        this.marStateAssess = marStateAssess;
    }

	@Column(name = "`APR_STATE_ASSESS`")
	private Double aprStateAssess;

    public Double getAprStateAssess () {
        return this.aprStateAssess;
    }

    public void setAprStateAssess (Double aprStateAssess) {
        this.aprStateAssess = aprStateAssess;
    }

	@Column(name = "`MAY_STATE_ASSESS`")
	private Double mayStateAssess;

    public Double getMayStateAssess () {
        return this.mayStateAssess;
    }

    public void setMayStateAssess (Double mayStateAssess) {
        this.mayStateAssess = mayStateAssess;
    }

	@Column(name = "`JUN_STATE_ASSESS`")
	private Double junStateAssess;

    public Double getJunStateAssess () {
        return this.junStateAssess;
    }

    public void setJunStateAssess (Double junStateAssess) {
        this.junStateAssess = junStateAssess;
    }

	@Column(name = "`JUL_STATE_ASSESS`")
	private Double julStateAssess;

    public Double getJulStateAssess () {
        return this.julStateAssess;
    }

    public void setJulStateAssess (Double julStateAssess) {
        this.julStateAssess = julStateAssess;
    }

	@Column(name = "`AUG_STATE_ASSESS`")
	private Double augStateAssess;

    public Double getAugStateAssess () {
        return this.augStateAssess;
    }

    public void setAugStateAssess (Double augStateAssess) {
        this.augStateAssess = augStateAssess;
    }

	@Column(name = "`SEP_STATE_ASSESS`")
	private Double sepStateAssess;

    public Double getSepStateAssess () {
        return this.sepStateAssess;
    }

    public void setSepStateAssess (Double sepStateAssess) {
        this.sepStateAssess = sepStateAssess;
    }

	@Column(name = "`OCT_STATE_ASSESS`")
	private Double octStateAssess;

    public Double getOctStateAssess () {
        return this.octStateAssess;
    }

    public void setOctStateAssess (Double octStateAssess) {
        this.octStateAssess = octStateAssess;
    }

	@Column(name = "`NOV_STATE_ASSESS`")
	private Double novStateAssess;

    public Double getNovStateAssess () {
        return this.novStateAssess;
    }

    public void setNovStateAssess (Double novStateAssess) {
        this.novStateAssess = novStateAssess;
    }

	@Column(name = "`DEC_STATE_ASSESS`")
	private Double decStateAssess;

    public Double getDecStateAssess () {
        return this.decStateAssess;
    }

    public void setDecStateAssess (Double decStateAssess) {
        this.decStateAssess = decStateAssess;
    }

	@Column(name = "`JAN_TOT_FUND_GT3`")
	private Double janTotFundGt3;

    public Double getJanTotFundGt3 () {
        return this.janTotFundGt3;
    }

    public void setJanTotFundGt3 (Double janTotFundGt3) {
        this.janTotFundGt3 = janTotFundGt3;
    }

	@Column(name = "`FEB_TOT_FUND_GT3`")
	private Double febTotFundGt3;

    public Double getFebTotFundGt3 () {
        return this.febTotFundGt3;
    }

    public void setFebTotFundGt3 (Double febTotFundGt3) {
        this.febTotFundGt3 = febTotFundGt3;
    }

	@Column(name = "`MAR_TOT_FUND_GT3`")
	private Double marTotFundGt3;

    public Double getMarTotFundGt3 () {
        return this.marTotFundGt3;
    }

    public void setMarTotFundGt3 (Double marTotFundGt3) {
        this.marTotFundGt3 = marTotFundGt3;
    }

	@Column(name = "`APR_TOT_FUND_GT3`")
	private Double aprTotFundGt3;

    public Double getAprTotFundGt3 () {
        return this.aprTotFundGt3;
    }

    public void setAprTotFundGt3 (Double aprTotFundGt3) {
        this.aprTotFundGt3 = aprTotFundGt3;
    }

	@Column(name = "`MAY_TOT_FUND_GT3`")
	private Double mayTotFundGt3;

    public Double getMayTotFundGt3 () {
        return this.mayTotFundGt3;
    }

    public void setMayTotFundGt3 (Double mayTotFundGt3) {
        this.mayTotFundGt3 = mayTotFundGt3;
    }

	@Column(name = "`JUN_TOT_FUND_GT3`")
	private Double junTotFundGt3;

    public Double getJunTotFundGt3 () {
        return this.junTotFundGt3;
    }

    public void setJunTotFundGt3 (Double junTotFundGt3) {
        this.junTotFundGt3 = junTotFundGt3;
    }

	@Column(name = "`JUL_TOT_FUND_GT3`")
	private Double julTotFundGt3;

    public Double getJulTotFundGt3 () {
        return this.julTotFundGt3;
    }

    public void setJulTotFundGt3 (Double julTotFundGt3) {
        this.julTotFundGt3 = julTotFundGt3;
    }

	@Column(name = "`AUG_TOT_FUND_GT3`")
	private Double augTotFundGt3;

    public Double getAugTotFundGt3 () {
        return this.augTotFundGt3;
    }

    public void setAugTotFundGt3 (Double augTotFundGt3) {
        this.augTotFundGt3 = augTotFundGt3;
    }

	@Column(name = "`SEP_TOT_FUND_GT3`")
	private Double sepTotFundGt3;

    public Double getSepTotFundGt3 () {
        return this.sepTotFundGt3;
    }

    public void setSepTotFundGt3 (Double sepTotFundGt3) {
        this.sepTotFundGt3 = sepTotFundGt3;
    }

	@Column(name = "`OCT_TOT_FUND_GT3`")
	private Double octTotFundGt3;

    public Double getOctTotFundGt3 () {
        return this.octTotFundGt3;
    }

    public void setOctTotFundGt3 (Double octTotFundGt3) {
        this.octTotFundGt3 = octTotFundGt3;
    }

	@Column(name = "`NOV_TOT_FUND_GT3`")
	private Double novTotFundGt3;

    public Double getNovTotFundGt3 () {
        return this.novTotFundGt3;
    }

    public void setNovTotFundGt3 (Double novTotFundGt3) {
        this.novTotFundGt3 = novTotFundGt3;
    }

	@Column(name = "`DEC_TOT_FUND_GT3`")
	private Double decTotFundGt3;

    public Double getDecTotFundGt3 () {
        return this.decTotFundGt3;
    }

    public void setDecTotFundGt3 (Double decTotFundGt3) {
        this.decTotFundGt3 = decTotFundGt3;
    }

	@Column(name = "`JAN_MM_CHRT_ADJ`")
	private Double janMmChrtAdj;

    public Double getJanMmChrtAdj () {
        return this.janMmChrtAdj;
    }

    public void setJanMmChrtAdj (Double janMmChrtAdj) {
        this.janMmChrtAdj = janMmChrtAdj;
    }

	@Column(name = "`FEB_MM_CHRT_ADJ`")
	private Double febMmChrtAdj;

    public Double getFebMmChrtAdj () {
        return this.febMmChrtAdj;
    }

    public void setFebMmChrtAdj (Double febMmChrtAdj) {
        this.febMmChrtAdj = febMmChrtAdj;
    }

	@Column(name = "`MAR_MM_CHRT_ADJ`")
	private Double marMmChrtAdj;

    public Double getMarMmChrtAdj () {
        return this.marMmChrtAdj;
    }

    public void setMarMmChrtAdj (Double marMmChrtAdj) {
        this.marMmChrtAdj = marMmChrtAdj;
    }

	@Column(name = "`APR_MM_CHRT_ADJ`")
	private Double aprMmChrtAdj;

    public Double getAprMmChrtAdj () {
        return this.aprMmChrtAdj;
    }

    public void setAprMmChrtAdj (Double aprMmChrtAdj) {
        this.aprMmChrtAdj = aprMmChrtAdj;
    }

	@Column(name = "`MAY_MM_CHRT_ADJ`")
	private Double mayMmChrtAdj;

    public Double getMayMmChrtAdj () {
        return this.mayMmChrtAdj;
    }

    public void setMayMmChrtAdj (Double mayMmChrtAdj) {
        this.mayMmChrtAdj = mayMmChrtAdj;
    }

	@Column(name = "`JUN_MM_CHRT_ADJ`")
	private Double junMmChrtAdj;

    public Double getJunMmChrtAdj () {
        return this.junMmChrtAdj;
    }

    public void setJunMmChrtAdj (Double junMmChrtAdj) {
        this.junMmChrtAdj = junMmChrtAdj;
    }

	@Column(name = "`JUL_MM_CHRT_ADJ`")
	private Double julMmChrtAdj;

    public Double getJulMmChrtAdj () {
        return this.julMmChrtAdj;
    }

    public void setJulMmChrtAdj (Double julMmChrtAdj) {
        this.julMmChrtAdj = julMmChrtAdj;
    }

	@Column(name = "`AUG_MM_CHRT_ADJ`")
	private Double augMmChrtAdj;

    public Double getAugMmChrtAdj () {
        return this.augMmChrtAdj;
    }

    public void setAugMmChrtAdj (Double augMmChrtAdj) {
        this.augMmChrtAdj = augMmChrtAdj;
    }

	@Column(name = "`SEP_MM_CHRT_ADJ`")
	private Double sepMmChrtAdj;

    public Double getSepMmChrtAdj () {
        return this.sepMmChrtAdj;
    }

    public void setSepMmChrtAdj (Double sepMmChrtAdj) {
        this.sepMmChrtAdj = sepMmChrtAdj;
    }

	@Column(name = "`OCT_MM_CHRT_ADJ`")
	private Double octMmChrtAdj;

    public Double getOctMmChrtAdj () {
        return this.octMmChrtAdj;
    }

    public void setOctMmChrtAdj (Double octMmChrtAdj) {
        this.octMmChrtAdj = octMmChrtAdj;
    }

	@Column(name = "`NOV_MM_CHRT_ADJ`")
	private Double novMmChrtAdj;

    public Double getNovMmChrtAdj () {
        return this.novMmChrtAdj;
    }

    public void setNovMmChrtAdj (Double novMmChrtAdj) {
        this.novMmChrtAdj = novMmChrtAdj;
    }

	@Column(name = "`DEC_MM_CHRT_ADJ`")
	private Double decMmChrtAdj;

    public Double getDecMmChrtAdj () {
        return this.decMmChrtAdj;
    }

    public void setDecMmChrtAdj (Double decMmChrtAdj) {
        this.decMmChrtAdj = decMmChrtAdj;
    }

	@Column(name = "`JAN_MM_O_CDE_ADJ`")
	private Double janMmOCdeAdj;

    public Double getJanMmOCdeAdj () {
        return this.janMmOCdeAdj;
    }

    public void setJanMmOCdeAdj (Double janMmOCdeAdj) {
        this.janMmOCdeAdj = janMmOCdeAdj;
    }

	@Column(name = "`FEB_MM_O_CDE_ADJ`")
	private Double febMmOCdeAdj;

    public Double getFebMmOCdeAdj () {
        return this.febMmOCdeAdj;
    }

    public void setFebMmOCdeAdj (Double febMmOCdeAdj) {
        this.febMmOCdeAdj = febMmOCdeAdj;
    }

	@Column(name = "`MAR_MM_O_CDE_ADJ`")
	private Double marMmOCdeAdj;

    public Double getMarMmOCdeAdj () {
        return this.marMmOCdeAdj;
    }

    public void setMarMmOCdeAdj (Double marMmOCdeAdj) {
        this.marMmOCdeAdj = marMmOCdeAdj;
    }

	@Column(name = "`APR_MM_O_CDE_ADJ`")
	private Double aprMmOCdeAdj;

    public Double getAprMmOCdeAdj () {
        return this.aprMmOCdeAdj;
    }

    public void setAprMmOCdeAdj (Double aprMmOCdeAdj) {
        this.aprMmOCdeAdj = aprMmOCdeAdj;
    }

	@Column(name = "`MAY_MM_O_CDE_ADJ`")
	private Double mayMmOCdeAdj;

    public Double getMayMmOCdeAdj () {
        return this.mayMmOCdeAdj;
    }

    public void setMayMmOCdeAdj (Double mayMmOCdeAdj) {
        this.mayMmOCdeAdj = mayMmOCdeAdj;
    }

	@Column(name = "`JUN_MM_O_CDE_ADJ`")
	private Double junMmOCdeAdj;

    public Double getJunMmOCdeAdj () {
        return this.junMmOCdeAdj;
    }

    public void setJunMmOCdeAdj (Double junMmOCdeAdj) {
        this.junMmOCdeAdj = junMmOCdeAdj;
    }

	@Column(name = "`JUL_MM_O_CDE_ADJ`")
	private Double julMmOCdeAdj;

    public Double getJulMmOCdeAdj () {
        return this.julMmOCdeAdj;
    }

    public void setJulMmOCdeAdj (Double julMmOCdeAdj) {
        this.julMmOCdeAdj = julMmOCdeAdj;
    }

	@Column(name = "`AUG_MM_O_CDE_ADJ`")
	private Double augMmOCdeAdj;

    public Double getAugMmOCdeAdj () {
        return this.augMmOCdeAdj;
    }

    public void setAugMmOCdeAdj (Double augMmOCdeAdj) {
        this.augMmOCdeAdj = augMmOCdeAdj;
    }

	@Column(name = "`SEP_MM_O_CDE_ADJ`")
	private Double sepMmOCdeAdj;

    public Double getSepMmOCdeAdj () {
        return this.sepMmOCdeAdj;
    }

    public void setSepMmOCdeAdj (Double sepMmOCdeAdj) {
        this.sepMmOCdeAdj = sepMmOCdeAdj;
    }

	@Column(name = "`OCT_MM_O_CDE_ADJ`")
	private Double octMmOCdeAdj;

    public Double getOctMmOCdeAdj () {
        return this.octMmOCdeAdj;
    }

    public void setOctMmOCdeAdj (Double octMmOCdeAdj) {
        this.octMmOCdeAdj = octMmOCdeAdj;
    }

	@Column(name = "`NOV_MM_O_CDE_ADJ`")
	private Double novMmOCdeAdj;

    public Double getNovMmOCdeAdj () {
        return this.novMmOCdeAdj;
    }

    public void setNovMmOCdeAdj (Double novMmOCdeAdj) {
        this.novMmOCdeAdj = novMmOCdeAdj;
    }

	@Column(name = "`DEC_MM_O_CDE_ADJ`")
	private Double decMmOCdeAdj;

    public Double getDecMmOCdeAdj () {
        return this.decMmOCdeAdj;
    }

    public void setDecMmOCdeAdj (Double decMmOCdeAdj) {
        this.decMmOCdeAdj = decMmOCdeAdj;
    }

	@Column(name = "`JAN_MM_AUDIT_ADJ`")
	private Double janMmAuditAdj;

    public Double getJanMmAuditAdj () {
        return this.janMmAuditAdj;
    }

    public void setJanMmAuditAdj (Double janMmAuditAdj) {
        this.janMmAuditAdj = janMmAuditAdj;
    }

	@Column(name = "`FEB_MM_AUDIT_ADJ`")
	private Double febMmAuditAdj;

    public Double getFebMmAuditAdj () {
        return this.febMmAuditAdj;
    }

    public void setFebMmAuditAdj (Double febMmAuditAdj) {
        this.febMmAuditAdj = febMmAuditAdj;
    }

	@Column(name = "`MAR_MM_AUDIT_ADJ`")
	private Double marMmAuditAdj;

    public Double getMarMmAuditAdj () {
        return this.marMmAuditAdj;
    }

    public void setMarMmAuditAdj (Double marMmAuditAdj) {
        this.marMmAuditAdj = marMmAuditAdj;
    }

	@Column(name = "`APR_MM_AUDIT_ADJ`")
	private Double aprMmAuditAdj;

    public Double getAprMmAuditAdj () {
        return this.aprMmAuditAdj;
    }

    public void setAprMmAuditAdj (Double aprMmAuditAdj) {
        this.aprMmAuditAdj = aprMmAuditAdj;
    }

	@Column(name = "`MAY_MM_AUDIT_ADJ`")
	private Double mayMmAuditAdj;

    public Double getMayMmAuditAdj () {
        return this.mayMmAuditAdj;
    }

    public void setMayMmAuditAdj (Double mayMmAuditAdj) {
        this.mayMmAuditAdj = mayMmAuditAdj;
    }

	@Column(name = "`JUN_MM_AUDIT_ADJ`")
	private Double junMmAuditAdj;

    public Double getJunMmAuditAdj () {
        return this.junMmAuditAdj;
    }

    public void setJunMmAuditAdj (Double junMmAuditAdj) {
        this.junMmAuditAdj = junMmAuditAdj;
    }

	@Column(name = "`JUL_MM_AUDIT_ADJ`")
	private Double julMmAuditAdj;

    public Double getJulMmAuditAdj () {
        return this.julMmAuditAdj;
    }

    public void setJulMmAuditAdj (Double julMmAuditAdj) {
        this.julMmAuditAdj = julMmAuditAdj;
    }

	@Column(name = "`AUG_MM_AUDIT_ADJ`")
	private Double augMmAuditAdj;

    public Double getAugMmAuditAdj () {
        return this.augMmAuditAdj;
    }

    public void setAugMmAuditAdj (Double augMmAuditAdj) {
        this.augMmAuditAdj = augMmAuditAdj;
    }

	@Column(name = "`SEP_MM_AUDIT_ADJ`")
	private Double sepMmAuditAdj;

    public Double getSepMmAuditAdj () {
        return this.sepMmAuditAdj;
    }

    public void setSepMmAuditAdj (Double sepMmAuditAdj) {
        this.sepMmAuditAdj = sepMmAuditAdj;
    }

	@Column(name = "`OCT_MM_AUDIT_ADJ`")
	private Double octMmAuditAdj;

    public Double getOctMmAuditAdj () {
        return this.octMmAuditAdj;
    }

    public void setOctMmAuditAdj (Double octMmAuditAdj) {
        this.octMmAuditAdj = octMmAuditAdj;
    }

	@Column(name = "`NOV_MM_AUDIT_ADJ`")
	private Double novMmAuditAdj;

    public Double getNovMmAuditAdj () {
        return this.novMmAuditAdj;
    }

    public void setNovMmAuditAdj (Double novMmAuditAdj) {
        this.novMmAuditAdj = novMmAuditAdj;
    }

	@Column(name = "`DEC_MM_AUDIT_ADJ`")
	private Double decMmAuditAdj;

    public Double getDecMmAuditAdj () {
        return this.decMmAuditAdj;
    }

    public void setDecMmAuditAdj (Double decMmAuditAdj) {
        this.decMmAuditAdj = decMmAuditAdj;
    }

}