
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`ST_EQ_LUNCH`")
public class StEqLunch implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`DATE_CHANGE`")
	private String dateChange;

    public String getDateChange () {
        return this.dateChange;
    }

    public void setDateChange (String dateChange) {
        this.dateChange = dateChange;
    }

	@Column(name = "`CHANGE_TYPE`")
	private String changeType;

    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

	@Column(name = "`LUNCH_F_CPP`")
	private Long lunchFCpp;

    public Long getLunchFCpp () {
        return this.lunchFCpp;
    }

    public void setLunchFCpp (Long lunchFCpp) {
        this.lunchFCpp = lunchFCpp;
    }

	@Column(name = "`LUNCH_F_K`")
	private Long lunchFK;

    public Long getLunchFK () {
        return this.lunchFK;
    }

    public void setLunchFK (Long lunchFK) {
        this.lunchFK = lunchFK;
    }

	@Column(name = "`FULL_K_F_LUNCH`")
	private Long fullKFLunch;

    public Long getFullKFLunch () {
        return this.fullKFLunch;
    }

    public void setFullKFLunch (Long fullKFLunch) {
        this.fullKFLunch = fullKFLunch;
    }

	@Column(name = "`LUNCH_F_1`")
	private Long lunchF1;

    public Long getLunchF1 () {
        return this.lunchF1;
    }

    public void setLunchF1 (Long lunchF1) {
        this.lunchF1 = lunchF1;
    }

	@Column(name = "`LUNCH_F_2`")
	private Long lunchF2;

    public Long getLunchF2 () {
        return this.lunchF2;
    }

    public void setLunchF2 (Long lunchF2) {
        this.lunchF2 = lunchF2;
    }

	@Column(name = "`LUNCH_F_3`")
	private Long lunchF3;

    public Long getLunchF3 () {
        return this.lunchF3;
    }

    public void setLunchF3 (Long lunchF3) {
        this.lunchF3 = lunchF3;
    }

	@Column(name = "`LUNCH_F_4`")
	private Long lunchF4;

    public Long getLunchF4 () {
        return this.lunchF4;
    }

    public void setLunchF4 (Long lunchF4) {
        this.lunchF4 = lunchF4;
    }

	@Column(name = "`LUNCH_F_5`")
	private Long lunchF5;

    public Long getLunchF5 () {
        return this.lunchF5;
    }

    public void setLunchF5 (Long lunchF5) {
        this.lunchF5 = lunchF5;
    }

	@Column(name = "`LUNCH_F_6`")
	private Long lunchF6;

    public Long getLunchF6 () {
        return this.lunchF6;
    }

    public void setLunchF6 (Long lunchF6) {
        this.lunchF6 = lunchF6;
    }

	@Column(name = "`LUNCH_F_7`")
	private Long lunchF7;

    public Long getLunchF7 () {
        return this.lunchF7;
    }

    public void setLunchF7 (Long lunchF7) {
        this.lunchF7 = lunchF7;
    }

	@Column(name = "`LUNCH_F_8`")
	private Long lunchF8;

    public Long getLunchF8 () {
        return this.lunchF8;
    }

    public void setLunchF8 (Long lunchF8) {
        this.lunchF8 = lunchF8;
    }

	@Column(name = "`LUNCH_F_9`")
	private Long lunchF9;

    public Long getLunchF9 () {
        return this.lunchF9;
    }

    public void setLunchF9 (Long lunchF9) {
        this.lunchF9 = lunchF9;
    }

	@Column(name = "`LUNCH_F_10`")
	private Long lunchF10;

    public Long getLunchF10 () {
        return this.lunchF10;
    }

    public void setLunchF10 (Long lunchF10) {
        this.lunchF10 = lunchF10;
    }

	@Column(name = "`LUNCH_F_11`")
	private Long lunchF11;

    public Long getLunchF11 () {
        return this.lunchF11;
    }

    public void setLunchF11 (Long lunchF11) {
        this.lunchF11 = lunchF11;
    }

	@Column(name = "`LUNCH_F_12`")
	private Long lunchF12;

    public Long getLunchF12 () {
        return this.lunchF12;
    }

    public void setLunchF12 (Long lunchF12) {
        this.lunchF12 = lunchF12;
    }

	@Column(name = "`SP_7_12_F_LUNCH`")
	private Long sp712FLunch;

    public Long getSp712FLunch () {
        return this.sp712FLunch;
    }

    public void setSp712FLunch (Long sp712FLunch) {
        this.sp712FLunch = sp712FLunch;
    }

	@Column(name = "`UN_F_LUNCH`")
	private Long unFLunch;

    public Long getUnFLunch () {
        return this.unFLunch;
    }

    public void setUnFLunch (Long unFLunch) {
        this.unFLunch = unFLunch;
    }

	@Column(name = "`LUNCH_F_TOT`")
	private Long lunchFTot;

    public Long getLunchFTot () {
        return this.lunchFTot;
    }

    public void setLunchFTot (Long lunchFTot) {
        this.lunchFTot = lunchFTot;
    }

	@Column(name = "`SP_K6_F_LUNCH`")
	private Long spK6FLunch;

    public Long getSpK6FLunch () {
        return this.spK6FLunch;
    }

    public void setSpK6FLunch (Long spK6FLunch) {
        this.spK6FLunch = spK6FLunch;
    }

}