
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer. Every
 * business object has a primary key that is exposed through getPrimaryKey() and
 * setPrimaryKey() methods. Please note that the business object also exposes
 * getter and setter methods for individual components (fields) of the primary
 * key. For example, if a business object has a field named "Id" as a primary
 * key field, it can be obtained via getId().
 * 
 * @see com.resqsoft.biz.PrimaryKey
 * @see com.resqsoft.biz.BusinessObject
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "Adjustment")
public class Adjustment implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column
	private Long adjustmentNumber;

    public Long getAdjustmentNumber () {
        return this.adjustmentNumber;
    }

    public void setAdjustmentNumber (Long adjustmentNumber) {
        this.adjustmentNumber = adjustmentNumber;
    }

	@Column
	private String districtName;

    public String getDistrictName () {
        return this.districtName;
    }

    public void setDistrictName (String districtName) {
        this.districtName = districtName;
    }

	@Column
	private String districtCode;

    public String getDistrictCode () {
        return this.districtCode;
    }

    public void setDistrictCode (String districtCode) {
        this.districtCode = districtCode;
    }

	@Column
	private String active;

    public String getActive () {
        return this.active;
    }

    public void setActive (String active) {
        this.active = active;
    }

	@Column
	private String begFiscalYear;

    public String getBegFiscalYear () {
        return this.begFiscalYear;
    }

    public void setBegFiscalYear (String begFiscalYear) {
        this.begFiscalYear = begFiscalYear;
    }

	@Column
	private String begFiscalMonth;

    public String getBegFiscalMonth () {
        return this.begFiscalMonth;
    }

    public void setBegFiscalMonth (String begFiscalMonth) {
        this.begFiscalMonth = begFiscalMonth;
    }

	@Column
	private String endFiscalYear;

    public String getEndFiscalYear () {
        return this.endFiscalYear;
    }

    public void setEndFiscalYear (String endFiscalYear) {
        this.endFiscalYear = endFiscalYear;
    }

	@Column
	private String endFiscalMonth;

    public String getEndFiscalMonth () {
        return this.endFiscalMonth;
    }

    public void setEndFiscalMonth (String endFiscalMonth) {
        this.endFiscalMonth = endFiscalMonth;
    }

	@Column
	private String frequency;

    public String getFrequency () {
        return this.frequency;
    }

    public void setFrequency (String frequency) {
        this.frequency = frequency;
    }

	@Column
	private String adjustmentType;

    public String getAdjustmentType () {
        return this.adjustmentType;
    }

    public void setAdjustmentType (String adjustmentType) {
        this.adjustmentType = adjustmentType;
    }

	@Column
	private Long amount;

    public Long getAmount () {
        return this.amount;
    }

    public void setAmount (Long amount) {
        this.amount = amount;
    }

	@Column
	private String notes;

    public String getNotes () {
        return this.notes;
    }

    public void setNotes (String notes) {
        this.notes = notes;
    }

}