
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`AUDIT_LUNCH`")
public class AuditLunch implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`AUDIT_ID`")
	private Integer auditId;

    public Integer getAuditId () {
        return this.auditId;
    }

    public void setAuditId (Integer auditId) {
        this.auditId = auditId;
    }

	@Column(name = "`FISCAL_YEAR`")
	private String fiscalYear;

    public String getFiscalYear () {
        return this.fiscalYear;
    }

    public void setFiscalYear (String fiscalYear) {
        this.fiscalYear = fiscalYear;
    }

	@Column(name = "`TOT_F_LUNCH`")
	private Double totFLunch;

    public Double getTotFLunch () {
        return this.totFLunch;
    }

    public void setTotFLunch (Double totFLunch) {
        this.totFLunch = totFLunch;
    }

	@Column(name = "`UN_F_LUNCH`")
	private Double unFLunch;

    public Double getUnFLunch () {
        return this.unFLunch;
    }

    public void setUnFLunch (Double unFLunch) {
        this.unFLunch = unFLunch;
    }

	@Column(name = "`SP_7_12_F_LUNCH`")
	private Double sp712FLunch;

    public Double getSp712FLunch () {
        return this.sp712FLunch;
    }

    public void setSp712FLunch (Double sp712FLunch) {
        this.sp712FLunch = sp712FLunch;
    }

	@Column(name = "`TWTH_F_LUNCH`")
	private Double twthFLunch;

    public Double getTwthFLunch () {
        return this.twthFLunch;
    }

    public void setTwthFLunch (Double twthFLunch) {
        this.twthFLunch = twthFLunch;
    }

	@Column(name = "`ELVN_F_LUNCH`")
	private Double elvnFLunch;

    public Double getElvnFLunch () {
        return this.elvnFLunch;
    }

    public void setElvnFLunch (Double elvnFLunch) {
        this.elvnFLunch = elvnFLunch;
    }

	@Column(name = "`TEN_F_LUNCH`")
	private Double tenFLunch;

    public Double getTenFLunch () {
        return this.tenFLunch;
    }

    public void setTenFLunch (Double tenFLunch) {
        this.tenFLunch = tenFLunch;
    }

	@Column(name = "`NTH_F_LUNCH`")
	private Double nthFLunch;

    public Double getNthFLunch () {
        return this.nthFLunch;
    }

    public void setNthFLunch (Double nthFLunch) {
        this.nthFLunch = nthFLunch;
    }

	@Column(name = "`EGHT_F_LUNCH`")
	private Double eghtFLunch;

    public Double getEghtFLunch () {
        return this.eghtFLunch;
    }

    public void setEghtFLunch (Double eghtFLunch) {
        this.eghtFLunch = eghtFLunch;
    }

	@Column(name = "`SVN_F_LUNCH`")
	private Double svnFLunch;

    public Double getSvnFLunch () {
        return this.svnFLunch;
    }

    public void setSvnFLunch (Double svnFLunch) {
        this.svnFLunch = svnFLunch;
    }

	@Column(name = "`SP_K6_F_LUNCH`")
	private Double spK6FLunch;

    public Double getSpK6FLunch () {
        return this.spK6FLunch;
    }

    public void setSpK6FLunch (Double spK6FLunch) {
        this.spK6FLunch = spK6FLunch;
    }

	@Column(name = "`SIX_F_LUNCH`")
	private Double sixFLunch;

    public Double getSixFLunch () {
        return this.sixFLunch;
    }

    public void setSixFLunch (Double sixFLunch) {
        this.sixFLunch = sixFLunch;
    }

	@Column(name = "`FFTH_F_LUNCH`")
	private Double ffthFLunch;

    public Double getFfthFLunch () {
        return this.ffthFLunch;
    }

    public void setFfthFLunch (Double ffthFLunch) {
        this.ffthFLunch = ffthFLunch;
    }

	@Column(name = "`FRTH_F_LUNCH`")
	private Double frthFLunch;

    public Double getFrthFLunch () {
        return this.frthFLunch;
    }

    public void setFrthFLunch (Double frthFLunch) {
        this.frthFLunch = frthFLunch;
    }

	@Column(name = "`THD_F_LUNCH`")
	private Double thdFLunch;

    public Double getThdFLunch () {
        return this.thdFLunch;
    }

    public void setThdFLunch (Double thdFLunch) {
        this.thdFLunch = thdFLunch;
    }

	@Column(name = "`SEC_F_LUNCH`")
	private Double secFLunch;

    public Double getSecFLunch () {
        return this.secFLunch;
    }

    public void setSecFLunch (Double secFLunch) {
        this.secFLunch = secFLunch;
    }

	@Column(name = "`FST_F_LUNCH`")
	private Double fstFLunch;

    public Double getFstFLunch () {
        return this.fstFLunch;
    }

    public void setFstFLunch (Double fstFLunch) {
        this.fstFLunch = fstFLunch;
    }

	@Column(name = "`FULL_K_F_LUNCH`")
	private Double fullKFLunch;

    public Double getFullKFLunch () {
        return this.fullKFLunch;
    }

    public void setFullKFLunch (Double fullKFLunch) {
        this.fullKFLunch = fullKFLunch;
    }

	@Column(name = "`KIND_F_LUNCH`")
	private Double kindFLunch;

    public Double getKindFLunch () {
        return this.kindFLunch;
    }

    public void setKindFLunch (Double kindFLunch) {
        this.kindFLunch = kindFLunch;
    }

	@Column(name = "`PRE_F_LUNCH`")
	private Double preFLunch;

    public Double getPreFLunch () {
        return this.preFLunch;
    }

    public void setPreFLunch (Double preFLunch) {
        this.preFLunch = preFLunch;
    }

	@Column(name = "`CHANGE_TYPE`")
	private String changeType;

    public String getChangeType () {
        return this.changeType;
    }

    public void setChangeType (String changeType) {
        this.changeType = changeType;
    }

	@Column(name = "`DATE_CHANGED`")
	private String dateChanged;

    public String getDateChanged () {
        return this.dateChanged;
    }

    public void setDateChanged (String dateChanged) {
        this.dateChanged = dateChanged;
    }

	@Column(name = "`DISTRICT_NUMBER`")
	private String districtNumber;

    public String getDistrictNumber () {
        return this.districtNumber;
    }

    public void setDistrictNumber (String districtNumber) {
        this.districtNumber = districtNumber;
    }

}