
package com.cdoe.biz.model;

import java.util.Date;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * A persistable business object which is a part of the application's domain
 * model. Normally, but not necessarily a business object represents a mapping
 * to a database table in Web applications generated by ResQSoft Engineer.
 * 
 * @author ResQSoft, Inc. (ResQSoft Engineer)
 * @version $Revision: $
 */
@XmlRootElement
@Entity
@Table(name = "`ELECTIONS`")
public class Election implements Serializable {

	/**
	 * Explicit serialVersionUID is considered a best practice, but may not
	 * matter to developers in many cases. Explicit serialVersionUID generated
	 * to guard against risk of "unexpected InvalidClassExceptions during
	 * deserialization" due to variations in compiler implementations. Should be
	 * changed when definition (i.e. serializable attributes) of class changes
	 * _if_ there is any chance that an instance of this class has been
	 * serialized and will be deserialized later. This value should not be
	 * changed if the class definition has not changed.
	 * 
	 * References:
	 * http://java.sun.com/j2se/1.5.0/docs/api/java/io/Serializable.html
	 * http://www.javaworld.com/javaworld/javaqa/2003-06/02-qa-0627-mythser.html
	 * http://www.javapractices.com/Topic45.cjp
	 */
	private static final long serialVersionUID = 1L;
	
	/*
	 * Autogenerated field
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column
	private Long id;
	
	/**
	 * Hibernate provides optimistic locking through a version property on this persistent 
	 * object which is automatically managed by Hibernate. This version number will be used 
	 * by Hibernate to check that the row has not been updated since the last time it was 
	 * retrieved when updating the persistent object. 
	 * */
	@Version
	private Long version;
	
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}
	

	@Column(name = "`SBNT_AMOUNT`")
	private Double sbntAmount;

    public Double getSbntAmount () {
        return this.sbntAmount;
    }

    public void setSbntAmount (Double sbntAmount) {
        this.sbntAmount = sbntAmount;
    }

	@Column(name = "`TABOR_For`")
	private Long taborFor;

    public Long getTaborFor () {
        return this.taborFor;
    }

    public void setTaborFor (Long taborFor) {
        this.taborFor = taborFor;
    }

	@Column(name = "`TABOR_Against`")
	private Long taborAgainst;

    public Long getTaborAgainst () {
        return this.taborAgainst;
    }

    public void setTaborAgainst (Long taborAgainst) {
        this.taborAgainst = taborAgainst;
    }

	@Column(name = "`CAP_IMPROVE_LOAN_FOR`")
	private Long capImproveLoanFor;

    public Long getCapImproveLoanFor () {
        return this.capImproveLoanFor;
    }

    public void setCapImproveLoanFor (Long capImproveLoanFor) {
        this.capImproveLoanFor = capImproveLoanFor;
    }

	@Column(name = "`CAP_IMPROVE_LOAN_AGAINST`")
	private Long capImproveLoanAgainst;

    public Long getCapImproveLoanAgainst () {
        return this.capImproveLoanAgainst;
    }

    public void setCapImproveLoanAgainst (Long capImproveLoanAgainst) {
        this.capImproveLoanAgainst = capImproveLoanAgainst;
    }

	@Column(name = "`CAP_IMPROVE_LOAN_Amount`")
	private Long capImproveLoanAmount;

    public Long getCapImproveLoanAmount () {
        return this.capImproveLoanAmount;
    }

    public void setCapImproveLoanAmount (Long capImproveLoanAmount) {
        this.capImproveLoanAmount = capImproveLoanAmount;
    }

	@Column(name = "`CHARTER_SCHOOL_CAP_CONST_FOR`")
	private Long charterSchoolCapConstFor;

    public Long getCharterSchoolCapConstFor () {
        return this.charterSchoolCapConstFor;
    }

    public void setCharterSchoolCapConstFor (Long charterSchoolCapConstFor) {
        this.charterSchoolCapConstFor = charterSchoolCapConstFor;
    }

	@Column(name = "`CHARTER_SCHOOL_CAP_CONST_AGAINST`")
	private Long charterSchoolCapConstAgainst;

    public Long getCharterSchoolCapConstAgainst () {
        return this.charterSchoolCapConstAgainst;
    }

    public void setCharterSchoolCapConstAgainst (Long charterSchoolCapConstAgainst) {
        this.charterSchoolCapConstAgainst = charterSchoolCapConstAgainst;
    }

	@Column(name = "`CHARTER_SCHOOL_CAP_CONST_AMOUNT`")
	private Long charterSchoolCapConstAmount;

    public Long getCharterSchoolCapConstAmount () {
        return this.charterSchoolCapConstAmount;
    }

    public void setCharterSchoolCapConstAmount (Long charterSchoolCapConstAmount) {
        this.charterSchoolCapConstAmount = charterSchoolCapConstAmount;
    }

	@Column(name = "`OTHER_FOR`")
	private Long otherFor;

    public Long getOtherFor () {
        return this.otherFor;
    }

    public void setOtherFor (Long otherFor) {
        this.otherFor = otherFor;
    }

	@Column(name = "`OTHER_AGAINST`")
	private Long otherAgainst;

    public Long getOtherAgainst () {
        return this.otherAgainst;
    }

    public void setOtherAgainst (Long otherAgainst) {
        this.otherAgainst = otherAgainst;
    }

	@Column(name = "`BALLOT_LANGUAGE`")
	private String ballotLanguage;

    public String getBallotLanguage () {
        return this.ballotLanguage;
    }

    public void setBallotLanguage (String ballotLanguage) {
        this.ballotLanguage = ballotLanguage;
    }

}